# 4. Ensembles de Arboles de Decision

## 4.3 Random Forest

*Random Forest* es un algoritmo de ensembles de arboles de decision creado por Leo Brieman en 1995-2006
https://link.springer.com/content/pdf/10.1023/a:1010933404324.pdf

La página original es:
https://www.stat.berkeley.edu/~breiman/RandomForests/cc_home.htm

Dos buenos videos para seguir el paso a paso de Random Forest y aplicaciones:
* https://www.youtube.com/watch?v=J4Wdy0Wc_xQ
* https://www.youtube.com/watch?v=sQ870aTKqiM

Qué tipo de perturbaciones se realizan en Random Forest

*   Se perturba el dataset, con la técnica de bagging = Bootstrap Aggregating
*   Tambien se perturba el algoritmo, utiliza random en cada split

Cada arbolito de Random Forest se entrena sobre un dataset perturbado, que tiene :
* todas las columnas originales (esta es una GRAN diferencia con  Arboles Azarosos)
* la misma *cantidad* de registros del dataset original, PERO generados por la técnica de sampleo con reposición del dataset original.

A pesar de que Leo Brieman es también el inventor de CART (Classification and Regression Trees) Random Forest no corre el algoritmo CART de la libreria rpart, sino un CART perturbado, en donde cada split NO se hace sobre todos los campos del dataset, sino sobre un csubconjunto tomado al azar, esa cantidad es el hiperparámetro *mtry*

#### 4.3.1  Seteo del ambiente en Google Colab

Esta parte se debe correr con el runtime en Python3
<br>Ir al menu, Runtime -> Change Runtime Type -> Runtime type ->  **Python 3**

Conectar la virtual machine donde esta corriendo Google Colab con el  Google Drive, para poder tener persistencia de archivos

In [1]:
# primero establecer el Runtime de Python 3
from google.colab import drive
drive.mount('/content/.drive')

ERROR: Error in parse(text = input): <text>:2:6: unexpected symbol
1: # primero establecer el Runtime de Python 3
2: from google.colab
        ^

Para correr la siguiente celda es fundamental en Arranque en Frio haber copiado el archivo kaggle.json al Google Drive, en la carpeta indicada en el instructivo

<br>los siguientes comando estan en shell script de Linux
*   Crear las carpetas en el Google Drive
*   "instalar" el archivo kaggle.json desde el Google Drive a la virtual machine para que pueda ser utilizado por la libreria  kaggle de Python
*   Bajar el  **dataset_pequeno**  al  Google Drive  y tambien al disco local de la virtual machine que esta corriendo Google Colab

In [ ]:
%%shell

mkdir -p "/content/.drive/My Drive/dm"
mkdir -p "/content/buckets"
ln -s "/content/.drive/My Drive/dm" /content/buckets/b1

mkdir -p ~/.kaggle
cp /content/buckets/b1/kaggle/kaggle.json  ~/.kaggle
chmod 600 ~/.kaggle/kaggle.json


mkdir -p /content/buckets/b1/exp
mkdir -p /content/buckets/b1/datasets
mkdir -p /content/datasets



archivo_origen="https://storage.googleapis.com/open-courses/itba2025-8d0a/dataset_pequeno.csv"
archivo_destino="/content/datasets/dataset_pequeno.csv"
archivo_destino_bucket="/content/buckets/b1/datasets/dataset_pequeno.csv"

if ! test -f $archivo_destino_bucket; then
  wget  $archivo_origen  -O $archivo_destino_bucket
fi


if ! test -f $archivo_destino; then
  cp  $archivo_destino_bucket  $archivo_destino
fi

### 4.4  Random Forest, una corrida

El tiempo de corrida de este punto es de alrededor de 8 minutos

Esta parte se debe correr con el runtime en lenguaje **R** Ir al menu, Runtime -> Change Runtime Type -> Runtime type -> R

limpio el ambiente de R

In [2]:
format(Sys.time(), "%a %b %d %X %Y")

[1] "Sat Sep 20 22:53:57 2025"

In [3]:
# limpio la memoria
rm(list=ls(all.names=TRUE)) # remove all objects
gc(full=TRUE, verbose=FALSE) # garbage collection

       used    (Mb) gc trigger (Mb) max used (Mb)
Ncells  658215 35.2 1439388    76.9 1439388  76.9
Vcells 1227533  9.4 8388608    64.0 1924958  14.7

**ranger** es una de las muchas librerías en lenguage R que implementa el algoritmo *Random Forest*, tiene la ventaja que corre el paralelo, utilizando todos los nucleos del procesador.

In [4]:
# cargo las librerias que necesito
require("data.table")
require("rpart")

# ranger se usa para procesar
if( !require("ranger") ) install.packages("ranger")
require("ranger")

# randomForest  solo se usa para imputar nulos
if( !require("randomForest") ) install.packages("randomForest")
require("randomForest")

Loading required package: data.table

Loading required package: rpart

Loading required package: ranger

Loading required package: randomForest

randomForest 4.7-1.2

Type rfNews() to see new features/changes/bug fixes.


Attaching package: ‘randomForest’


The following object is masked from ‘package:ranger’:

    importance

Aqui debe cargar SU semilla primigenia y

In [5]:
PARAM <- list()
PARAM$experimento <- 440
PARAM$semilla_primigenia <- 999979

PARAM$ranger$num.trees <- 300 # cantidad de arboles
PARAM$ranger$mtry <- 13 # cantidad de atributos que participan en cada split
PARAM$ranger$min.node.size <- 50 # tamaño minimo de las hojas
PARAM$ranger$max.depth <- 10 # 0 significa profundidad infinita

In [6]:
# carpeta de trabajo
setwd("/content/buckets/b1/exp")
experimento_folder <- paste0("KA", PARAM$experimento)
dir.create(experimento_folder, showWarnings=FALSE)
setwd( paste0("/content/buckets/b1/exp/", experimento_folder ))

In [7]:
# lectura del dataset
dataset <- fread("/content/datasets/dataset_pequeno.csv")

In [8]:
#  estas dos lineas estan relacionadas con el Data Drifting
# asigno un valor muy negativo

if( "Master_Finiciomora" %in% colnames(dataset) )
  dataset[ is.na(Master_Finiciomora) , Master_Finiciomora := -999 ]

if( "Visa_Finiciomora" %in% colnames(dataset) )
  dataset[ is.na(Visa_Finiciomora) , Visa_Finiciomora :=  -999 ]

In [9]:
# defino los dataset de entrenamiento y aplicacion
dtrain <- dataset[foto_mes == 202107]
dfuture <- dataset[foto_mes == 202109]

In [10]:
set.seed( PARAM$semilla_primigenia ) # Establezco la semilla aleatoria


# ranger necesita la clase de tipo factor
factorizado <- as.factor(dtrain$clase_ternaria)
dtrain[, clase_ternaria := factorizado]

In [11]:
# Ranger NO acepta valores nulos
# Leo Breiman, ¿por que le temias a los nulos?
# imputo los nulos, ya que ranger no acepta nulos
dtrain <- na.roughfix(dtrain)

In [12]:
setorder(dtrain, clase_ternaria) # primero quedan los BAJA+1, BAJA+2, CONTINUA

# genero el modelo de Random Forest llamando a ranger()
modelo <- ranger(
  formula= "clase_ternaria ~ .",
  data= dtrain,
  probability= TRUE, # para que devuelva las probabilidades
  num.trees= PARAM$ranger$num.trees,
  mtry= PARAM$ranger$mtry,
  min.node.size= PARAM$ranger$min.node.size,
  max.depth= PARAM$ranger$max.depth
)

Growing trees.. Progress: 25%. Estimated remaining time: 1 minute, 31 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 58 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 27 seconds.

In [13]:
# Carpinteria necesaria sobre  dfuture
# como quiere la Estadistica Clasica, imputar nulos por separado
# ( aunque en este caso ya tengo los datos del futuro de antemano
#  pero bueno, sigamos el librito de estos fundamentalistas a rajatabla ...

dfuture[, clase_ternaria := NULL]
dfuture <- na.roughfix(dfuture)

In [14]:
tb_prediccion <- dfuture[, list(numero_de_cliente)]

In [15]:
# aplico el modelo a los datos que no tienen clase
# aplico el modelo recien creado a los datos del futuro
prediccion <- predict(modelo, dfuture)

tb_prediccion[, prob := prediccion$predictions[, "BAJA+2"] ]

In [16]:
tb_prediccion[, Predicted := as.numeric(prob > (1/40))]

In [17]:
archivo_kaggle <- paste0("KA", PARAM$experimento,".csv")

# grabo el archivo
fwrite( tb_prediccion[, list(numero_de_cliente, Predicted)],
 file= archivo_kaggle,
 sep= ","
)

In [18]:
# subida a Kaggle
comando <- "kaggle competitions submit"
competencia <- "-c data-mining-analista-sr-2025-b"
arch <- paste( "-f", archivo_kaggle)

mensaje <- paste0("-m 'num.trees=", PARAM$ranger$num.trees, "  mtry=", PARAM$ranger$mtry, "  min.node.size=", PARAM$ranger$min.node.size, " max.depth=", PARAM$ranger$max.depth, "'" )
linea <- paste( comando, competencia, arch, mensaje)
salida <- system(linea, intern= TRUE)
cat(salida)

Successfully submitted to Data Mining, Analista Sr 2025 B

In [19]:
format(Sys.time(), "%a %b %d %X %Y")

[1] "Sat Sep 20 23:00:36 2025"



---

### 4.5  Random Forest  optimizacion de hiperparámetros

Random Forest es un algoritmo que quedó obsoleto luego de la aparición de  XGBoost y LightGBM, debido a lo lento de las librerías que lo implementan.
<br> El siguiente script se brinda simplemente a modo pedagógico, advirtiendo a los alumn@s que demanda más de 24 horas para correr, y los resultados son mediocres.

limpio el ambiente de R

In [20]:
format(Sys.time(), "%a %b %d %X %Y")

[1] "Sat Sep 20 23:00:41 2025"

In [21]:
# limpio la memoria
rm(list=ls(all.names=TRUE)) # remove all objects
gc(full=TRUE, verbose=FALSE) # garbage collection

       used    (Mb) gc trigger (Mb)   max used  (Mb)
Ncells 1852920 99.0   6378770   340.7   4969926  265.5
Vcells 3344854 25.6 157885262  1204.6 193046810 1472.9

**ranger** es una de las muchas librerías en lenguage R que implementa el algoritmo *Random Forest*, tiene la ventaja que corre el paralelo, utilizando todos los nucleos del procesador.

In [22]:
# cargo las librerias que necesito
require("data.table")
require("rpart")
require("parallel")

if( !require("primes") ) install.packages("primes")
require("primes")

if( !require("rlist") ) install.packages("rlist")
require("rlist")

# ranger se usa para procesar
if( !require("ranger") ) install.packages("ranger")
require("ranger")

# randomForest  solo se usa para imputar nulos
if( !require("randomForest") ) install.packages("randomForest")
require("randomForest")


if( !require("DiceKriging") ) install.packages("DiceKriging")
require("DiceKriging")

if( !require("mlrMBO") ) install.packages("mlrMBO")
require("mlrMBO")

Loading required package: parallel

Loading required package: primes

Loading required package: rlist

Loading required package: DiceKriging

Loading required package: mlrMBO

Loading required package: mlr

Loading required package: ParamHelpers

Loading required package: smoof

Loading required package: checkmate


Attaching package: ‘checkmate’


The following object is masked from ‘package:DiceKriging’:

    checkNames

Aqui debe cargar SU semilla primigenia y

In [23]:
PARAM <- list()
PARAM$experimento <- 450
PARAM$semilla_primigenia <- 999979

PARAM$hyperparametertuning$iteraciones <- 100
PARAM$hyperparametertuning$xval_folds <- 5
PARAM$hyperparametertuning$POS_ganancia <- 117000
PARAM$hyperparametertuning$NEG_ganancia <- -3000

# Estructura que define los hiperparámetros y sus rangos
#  la letra L al final significa ENTERO
# max.depth 0 significa profundidad infinita
PARAM$hyperparametertuning$hs <- makeParamSet(
  makeIntegerParam("num.trees", lower= 20L, upper= 500L),
  makeIntegerParam("max.depth", lower= 1L, upper= 30L),
  makeIntegerParam("min.node.size", lower= 1L, upper= 1000L),
  makeIntegerParam("mtry", lower= 2L, upper= 50L)
)

In [24]:
# graba a un archivo los componentes de lista
# para el primer registro, escribe antes los titulos

loguear <- function(
    reg, arch= NA, folder= "./work/",
    ext= ".txt", verbose= TRUE) {

  archivo <- arch
  if (is.na(arch)) archivo <- paste0(folder, substitute(reg), ext)

  if (!file.exists(archivo)) # Escribo los titulos
    {
      linea <- paste0(
        "fecha\t",
        paste(list.names(reg), collapse= "\t"), "\n"
      )

      cat(linea, file= archivo)
    }

  linea <- paste0(
    format(Sys.time(), "%Y%m%d %H%M%S"), "\t", # la fecha y hora
    gsub(", ", "\t", toString(reg)), "\n"
  )

  cat(linea, file= archivo, append= TRUE) # grabo al archivo

  if (verbose) cat(linea) # imprimo por pantalla
}

In [25]:
# particionar agrega una columna llamada fold a un dataset
#  que consiste en una particion estratificada segun agrupa
# particionar( data=dataset, division=c(70,30),
#  agrupa=clase_ternaria, seed=semilla)   crea una particion 70, 30
# particionar( data=dataset, division=c(1,1,1,1,1),
#   agrupa=clase_ternaria, seed=semilla)   divide el dataset en 5 particiones

particionar <- function(
    data, division, agrupa= "",
    campo= "fold", start= 1, seed= NA) {

  if (!is.na(seed)) set.seed(seed)

  bloque <- unlist(mapply(function(x, y) {
    rep(y, x)
  }, division, seq(from= start, length.out= length(division))))

  data[, (campo) := sample(rep(bloque, ceiling(.N / length(bloque))))[1:.N],
    by= agrupa
  ]
}

In [26]:
# es un paso del Cross Validation
# utiliza el fold  fold_test para testear y el resto para entrenar

ranger_Simple <- function(fold_test, pdata, param) {
  # genero el modelo

  set.seed(PARAM$semillas[2])

  modelo <- ranger(
    formula= "clase_binaria ~ .",
    data= pdata[fold != fold_test],
    probability= TRUE, # para que devuelva las probabilidades
    num.trees= param$num.trees,
    mtry= param$mtry,
    min.node.size= param$min.node.size,
    max.depth= param$max.depth
  )

  prediccion <- predict(modelo, pdata[fold == fold_test])

  ganancia_testing <- pdata[
    fold == fold_test,
    sum((prediccion$predictions[, "POS"] > 1 / 40) *
      ifelse(clase_binaria == "POS",
        PARAM$hyperparametertuning$POS_ganancia,
        PARAM$hyperparametertuning$NEG_ganancia
      ))
  ]

  return(ganancia_testing)
}

In [27]:
# realiza Cross Validation, promediando las ganancias de los folds de testing

ranger_CrossValidation <- function(
    data, param,
    pcampos_buenos, qfolds, pagrupa, semilla) {

  divi <- rep(1, qfolds)
  particionar(data, divi, seed= semilla, agrupa= pagrupa)

  ganancias <- mcmapply(ranger_Simple,
    seq(qfolds), # 1 2 3 4 5
    MoreArgs= list(data, param),
    SIMPLIFY= FALSE,
    mc.cores= 1
  ) # dejar esto en  1, porque ranger ya corre en paralelo

  data[, fold := NULL] # elimino el campo fold

  # devuelvo la ganancia promedio normalizada
  ganancia_promedio <- mean(unlist(ganancias))
  ganancia_promedio_normalizada <- ganancia_promedio * qfolds

  return(ganancia_promedio_normalizada)
}

In [28]:
# esta funcion solo puede recibir los parametros que se estan optimizando
# el resto de los parametros se pasan como variables globales

EstimarGanancia_ranger <- function(x) {
  GLOBAL_iteracion <<- GLOBAL_iteracion + 1

  xval_folds <- PARAM$hyperparametertuning$xval_folds

  ganancia <- ranger_CrossValidation(dataset,
    param= x,
    qfolds= xval_folds,
    pagrupa= "clase_binaria",
    semilla= PARAM$semillas[1]
  )

  # logueo
  xx <- x
  xx$xval_folds <- xval_folds
  xx$ganancia <- ganancia
  xx$iteracion <- GLOBAL_iteracion
  loguear(xx, arch= klog)

  # si es ganancia superadora la almaceno en mejor
  if( ganancia > GLOBAL_mejor ) {
    GLOBAL_mejor <<- ganancia
    loguear(xx, arch= klog_mejor)
  }


  return(ganancia)
}

aqui se inicia el programa

In [29]:
# carpeta de trabajo
setwd("/content/buckets/b1/exp")
experimento_folder <- paste0("HT", PARAM$experimento)
dir.create(experimento_folder, showWarnings=FALSE)
setwd( paste0("/content/buckets/b1/exp/", experimento_folder ))

In [30]:
# genero numeros primos
primos <- generate_primes(min= 100000, max= 1000000)
set.seed(PARAM$semilla_primigenia) # inicializo
# me quedo con PARAM$qsemillas   semillas
PARAM$semillas <- sample(primos, 2 )

In [31]:
# lectura del dataset
dataset <- fread("/content/datasets/dataset_pequeno.csv", stringsAsFactors= TRUE)

In [32]:
dataset <- dataset[foto_mes %in% c(202107)]

In [33]:
#  estas dos lineas estan relacionadas con el Data Drifting
# asigno un valor muy negativo

if( "Master_Finiciomora" %in% colnames(dataset) )
  dataset[ is.na(Master_Finiciomora) , Master_Finiciomora := -999 ]

if( "Visa_Finiciomora" %in% colnames(dataset) )
  dataset[ is.na(Visa_Finiciomora) , Visa_Finiciomora :=  -999 ]

In [34]:
set.seed( PARAM$semilla_primigenia ) # Establezco la semilla aleatoria

In [35]:
# en estos archivos quedan los resultados
kbayesiana <- paste0("HT", PARAM$experimento, ".RDATA")
klog <- paste0("HT", PARAM$experimento, ".txt")
klog_mejor <- paste0("HT", PARAM$experimento, "_mejor.txt")

GLOBAL_iteracion <- 0 # inicializo la variable global
GLOBAL_mejor <- -Inf

# si ya existe el archivo log, traigo hasta donde llegue
if (file.exists(klog)) {
  tabla_log <- fread(klog)
  GLOBAL_iteracion <- nrow(tabla_log)
}

In [36]:
# paso a trabajar con clase binaria POS={BAJA+2}   NEG={BAJA+1, CONTINUA}
dataset[, clase_binaria :=
  as.factor(ifelse(clase_ternaria == "BAJA+2", "POS", "NEG"))]

dataset[, clase_ternaria := NULL] # elimino la clase_ternaria, ya no la necesito

In [37]:
# Ranger NO acepta valores nulos
# Leo Breiman, ¿por que le temias a los nulos?
# imputo los nulos, ya que ranger no acepta nulos

dataset <- na.roughfix(dataset)

In [38]:
# Aqui comienza la configuracion de la Bayesian Optimization

configureMlr(show.learner.output = FALSE)

funcion_optimizar <- EstimarGanancia_ranger

# configuro la busqueda bayesiana,  los hiperparametros que se van a optimizar
# por favor, no desesperarse por lo complejo
obj.fun <- makeSingleObjectiveFunction(
  fn= funcion_optimizar,
  minimize= FALSE, # estoy Maximizando la ganancia
  noisy= TRUE,
  par.set= PARAM$hyperparametertuning$hs,
  has.simple.signature= FALSE
)

ctrl <- makeMBOControl(save.on.disk.at.time= 600, save.file.path= kbayesiana)

ctrl <- setMBOControlTermination(
  ctrl,
  iters= PARAM$hyperparametertuning$iteraciones
)

ctrl <- setMBOControlInfill(ctrl, crit= makeMBOInfillCritEI())

surr.km <- makeLearner(
  "regr.km",
  predict.type= "se",
  covtype= "matern3_2",
  control= list(trace= TRUE)
)

In [39]:
# inicio la optimizacion bayesiana

if (!file.exists(kbayesiana)) {
  run <- mbo(obj.fun, learner= surr.km, control= ctrl)
} else {
  run <- mboContinue(kbayesiana)
} # retomo en caso que ya exista

Computing y column(s) for design. Not provided.

Growing trees.. Progress: 36%. Estimated remaining time: 54 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 22 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 53 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 20 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 50 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 19 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 20 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 20 seconds.
20250920 230913	118	10	417	34	5	53445000	1
20250920 230915	118	10	417	34	5	53445000	1
Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 31 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 6 minutes, 5 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 5 minutes, 28 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 4 minutes, 56 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 4 minutes, 26 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 3 minutes, 52 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 3 minutes, 20 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 2 minutes, 47 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 2 minutes, 16 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 1 minute, 43 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 12 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 8 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 6 minutes, 56 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 6 minutes, 11 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 5 minutes, 40 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 5 minutes, 8 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 4 minutes, 36 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 4 minutes, 3 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 3 minutes, 31 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 2 minutes, 59 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 2 minutes, 26 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 1 minute, 53 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 1 minute, 21 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 50 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 18 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 6 minutes, 30 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 5 minutes, 59 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 5 minutes, 28 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 4 minutes, 57 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 4 minutes, 26 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 3 minutes, 57 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 3 minutes, 25 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 2 minutes, 54 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 2 minutes, 23 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 1 minute, 52 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 1 minute, 20 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 48 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 17 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 6 minutes, 56 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 6 minutes, 18 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 5 minutes, 44 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 5 minutes, 12 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 4 minutes, 42 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 4 minutes, 8 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 3 minutes, 37 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 3 minutes, 5 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 2 minutes, 32 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 2 minutes, 1 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 1 minute, 29 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 57 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 25 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 6 minutes, 56 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 6 minutes, 11 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 5 minutes, 36 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 5 minutes, 3 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 4 minutes, 28 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 3 minutes, 53 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 3 minutes, 23 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 2 minutes, 50 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 2 minutes, 17 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 1 minute, 47 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 15 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 44 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 12 seconds.
20250920 234550	490	16	787	27	5	55371000	2
20250920 234552	490	16	787	27	5	55371000	2
Growing trees.. Progress: 30%. Estimated remaining time: 1 minute, 11 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 9 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 1 minute, 10 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 38 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 8 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 1 minute, 12 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 41 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 10 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 1 minute, 14 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 42 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 11 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 1 minute, 11 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 8 seconds.
20250920 235507	405	10	842	11	5	54609000	3
Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 30 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 53 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 5 minutes, 19 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 4 minutes, 46 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 4 minutes, 14 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 3 minutes, 39 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 3 minutes, 5 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 2 minutes, 35 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 2 minutes, 1 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 28 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 55 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 23 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 18 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 42 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 5 minutes, 12 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 4 minutes, 38 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 4 minutes, 11 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 3 minutes, 41 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 3 minutes, 10 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 2 minutes, 36 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 2 minutes, 5 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 34 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 29 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 18 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 5 minutes, 58 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 5 minutes, 26 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 5 minutes, 0 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 4 minutes, 24 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 3 minutes, 51 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 3 minutes, 18 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 2 minutes, 46 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 2 minutes, 12 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 1 minute, 38 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 4 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 33 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 30 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 6 minutes, 4 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 5 minutes, 18 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 4 minutes, 45 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 4 minutes, 14 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 3 minutes, 45 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 3 minutes, 13 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 2 minutes, 43 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 2 minutes, 12 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 1 minute, 38 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 5 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 33 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 6 minutes, 41 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 6 minutes, 4 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 5 minutes, 22 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 4 minutes, 46 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 4 minutes, 14 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 3 minutes, 41 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 3 minutes, 7 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 2 minutes, 33 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 2 minutes, 0 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 28 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 55 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 22 seconds.
20250921 003030	251	28	624	41	5	53211000	4
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 40 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 3 minutes, 9 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 2 minutes, 37 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 2 minutes, 4 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 1 minute, 32 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 59 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 25 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 3 minutes, 38 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 3 minutes, 4 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 2 minutes, 31 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 1 minute, 58 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 1 minute, 27 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 55 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 24 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 3 minutes, 31 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 3 minutes, 3 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 2 minutes, 30 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 1 minute, 57 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 1 minute, 26 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 54 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 23 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 3 minutes, 38 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 3 minutes, 4 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 2 minutes, 31 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 1 minute, 58 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 1 minute, 26 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 55 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 23 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 3 minutes, 38 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 3 minutes, 6 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 2 minutes, 32 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 2 minutes, 1 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 1 minute, 28 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 57 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 24 seconds.
20250921 005143	211	20	129	30	5	52776000	5
Growing trees.. Progress: 85%. Estimated remaining time: 5 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 6 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 5 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 6 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 6 seconds.
20250921 005507	71	6	977	49	5	52110000	6
Growing trees.. Progress: 27%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 57 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 26 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 57 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 25 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 55 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 25 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 1 minute, 32 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 1 minute, 1 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 29 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 1 minute, 32 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 1 minute, 0 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 28 seconds.
20250921 010543	147	26	358	21	5	54996000	7
Growing trees.. Progress: 14%. Estimated remaining time: 3 minutes, 9 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 2 minutes, 38 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 2 minutes, 5 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 1 minute, 35 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 1 minute, 3 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 32 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 3 minutes, 9 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 2 minutes, 33 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 2 minutes, 1 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 58 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 27 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 3 minutes, 4 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 2 minutes, 31 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 2 minutes, 1 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 1 minute, 31 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 1 minute, 0 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 28 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 3 minutes, 9 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 2 minutes, 38 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 2 minutes, 4 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 1 minute, 32 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 59 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 28 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 3 minutes, 14 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 2 minutes, 43 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 2 minutes, 10 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 1 minute, 38 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 1 minute, 6 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 35 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 4 seconds.
20250921 012449	334	24	102	17	5	52551000	8
Growing trees.. Progress: 68%. Estimated remaining time: 14 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 14 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 14 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 14 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 14 seconds.
20250921 012906	265	8	498	9	5	53535000	9
Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 25 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 3 minutes, 51 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 3 minutes, 21 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 2 minutes, 51 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 2 minutes, 21 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 1 minute, 49 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 1 minute, 17 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 45 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 13 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 14 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 3 minutes, 43 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 3 minutes, 12 seconds.

[mbo] 0: num.trees=118; max.depth=10; min.node.size=417; mtry=34 : y = 5.34e+07 : 438.5 secs : initdesign

[mbo] 0: num.trees=490; max.depth=16; min.node.size=787; mtry=27 : y = 5.54e+07 : 2197.3 secs : initdesign

[mbo] 0: num.trees=405; max.depth=10; min.node.size=842; mtry=11 : y = 5.46e+07 : 556.5 secs : initdesign

[mbo] 0: num.trees=251; max.depth=28; min.node.size=624; mtry=41 : y = 5.32e+07 : 2122.5 secs : initdesign

[mbo] 0: num.trees=211; max.depth=20; min.node.size=129; mtry=30 : y = 5.28e+07 : 1273.3 secs : initdesign

[mbo] 0: num.trees=71; max.depth=6; min.node.size=977; mtry=49 : y = 5.21e+07 : 204.0 secs : initdesign

[mbo] 0: num.trees=147; max.depth=26; min.node.size=358; mtry=21 : y = 5.5e+07 : 635.6 secs : initdesign

[mbo] 0: num.trees=334; max.depth=24; min.node.size=102; mtry=17 : y = 5.26e+07 : 1146.5 secs : initdesign

[mbo] 0: num.trees=265; max.depth=8; min.node.size=498; mtry=9 : y = 5.35e+07 : 256.9 secs : initdesign

[mbo] 0: num.trees=469; max.depth=23; min.node.size=721; mtry=17 : y = 5.46e+07 : 1499.5 secs : initdesign

[mbo] 0: num.trees=315; max.depth=1; min.node.size=536; mtry=46 : y = 4.3e+07 : 116.4 secs : initdesign

[mbo] 0: num.trees=376; max.depth=30; min.node.size=225; mtry=37 : y = 5.17e+07 : 3065.5 secs : initdesign

[mbo] 0: num.trees=186; max.depth=14; min.node.size=884; mtry=4 : y = 5.37e+07 : 175.8 secs : initdesign

[mbo] 0: num.trees=91; max.depth=19; min.node.size=664; mtry=42 : y = 5.42e+07 : 796.8 secs : initdesign

[mbo] 0: num.trees=34; max.depth=4; min.node.size=20; mtry=5 : y = 5.13e+07 : 21.5 secs : initdesign

[mbo] 0: num.trees=424; max.depth=13; min.node.size=266; mtry=26 : y = 5.48e+07 : 1682.0 secs : initdesign

Saved the current state after iteration 1 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 995 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 384 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 624 points instead of 1000!”

20250921 033222	20	26	1000	5	5	52956000	17

[mbo] 1: num.trees=20; max.depth=26; min.node.size=1000; mtry=5 : y = 5.3e+07 : 32.7 secs : infill_ei

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 594 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 594 points instead of 1000!”

Growing trees.. Progress: 5%. Estimated remaining time: 10 minutes, 34 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 10 minutes, 2 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 9 minutes, 30 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 8 minutes, 54 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 8 minutes, 18 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 7 minutes, 47 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 7 minutes, 10 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 6 minutes, 42 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 6 minutes, 6 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 5 minutes, 36 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 5 minutes, 2 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 4 minutes, 31 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 3 minutes, 59 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 3 minutes, 26 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 2 minutes, 57 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 2 minutes, 26 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 56 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 1 minute, 26 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 56 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 29 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 5 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 13 minutes, 30 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 13 minutes, 20 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 15 minutes, 11 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 15 minutes, 1 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 13 minutes, 33 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 12 minutes, 27 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 11 minutes, 29 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 10 minutes, 39 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 10 minutes, 6 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 9 minutes, 22 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 8 minutes, 42 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 7 minutes, 54 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 7 minutes, 10 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 6 minutes, 31 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 5 minutes, 48 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 5 minutes, 6 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 4 minutes, 28 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 3 minutes, 50 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 3 minutes, 14 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 2 minutes, 38 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 2 minutes, 3 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 1 minute, 29 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 55 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 20 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 11 minutes, 47 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 10 minutes, 58 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 10 minutes, 18 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 9 minutes, 54 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 9 minutes, 26 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 9 minutes, 20 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 9 minutes, 3 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 8 minutes, 31 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 8 minutes, 2 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 7 minutes, 35 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 7 minutes, 1 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 6 minutes, 30 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 5 minutes, 58 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 5 minutes, 23 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 4 minutes, 47 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 4 minutes, 11 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 3 minutes, 34 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 3 minutes, 2 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 2 minutes, 30 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 2 minutes, 0 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 28 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 54 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 21 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 12 minutes, 9 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 11 minutes, 20 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 10 minutes, 35 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 9 minutes, 58 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 9 minutes, 23 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 8 minutes, 47 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 8 minutes, 14 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 7 minutes, 39 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 7 minutes, 7 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 6 minutes, 38 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 6 minutes, 6 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 5 minutes, 30 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 4 minutes, 57 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 4 minutes, 24 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 3 minutes, 51 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 3 minutes, 17 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 2 minutes, 45 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 2 minutes, 12 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 40 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 1 minute, 6 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 32 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 2 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 11 minutes, 13 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 10 minutes, 37 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 9 minutes, 53 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 9 minutes, 20 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 8 minutes, 43 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 8 minutes, 11 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 7 minutes, 41 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 7 minutes, 10 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 6 minutes, 36 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 6 minutes, 4 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 5 minutes, 32 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 4 minutes, 59 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 4 minutes, 28 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 3 minutes, 54 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 3 minutes, 22 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 2 minutes, 50 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 2 minutes, 19 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 48 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 1 minute, 15 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 42 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 9 seconds.
20250921 043345	500	13	1000	48	5	54420000	18

[mbo] 2: num.trees=500; max.depth=13; min.node.size=1000; mtry=48 : y = 5.44e+07 : 3682.5 secs : infill_ei

Saved the current state after iteration 3 in the file HT450.RDATA.

Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 39 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 3 minutes, 6 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 2 minutes, 36 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 2 minutes, 4 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 1 minute, 33 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 1 minute, 3 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 39 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 3 minutes, 4 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 2 minutes, 33 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 2 minutes, 2 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 1 minute, 32 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 1 minute, 0 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 28 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 3 minutes, 31 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 3 minutes, 0 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 2 minutes, 26 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 1 minute, 54 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 1 minute, 23 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 51 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 20 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 3 minutes, 27 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 2 minutes, 52 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 2 minutes, 23 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 1 minute, 55 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 1 minute, 23 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 21 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 3 minutes, 27 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 2 minutes, 56 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 2 minutes, 26 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 1 minute, 57 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 54 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 24 seconds.
20250921 045515	500	17	532	14	5	54291000	19

[mbo] 3: num.trees=500; max.depth=17; min.node.size=532; mtry=14 : y = 5.43e+07 : 1287.0 secs : infill_ei

Saved the current state after iteration 4 in the file HT450.RDATA.

Growing trees.. Progress: 9%. Estimated remaining time: 5 minutes, 13 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 4 minutes, 42 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 4 minutes, 14 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 3 minutes, 42 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 3 minutes, 11 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 2 minutes, 42 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 2 minutes, 12 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 1 minute, 39 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 1 minute, 8 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 38 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 6 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 5 minutes, 29 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 4 minutes, 58 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 4 minutes, 27 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 3 minutes, 56 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 3 minutes, 25 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 2 minutes, 54 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 2 minutes, 23 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 1 minute, 49 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 17 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 46 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 14 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 5 minutes, 5 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 4 minutes, 35 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 4 minutes, 4 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 3 minutes, 32 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 3 minutes, 1 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 2 minutes, 31 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 2 minutes, 0 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 1 minute, 29 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 58 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 28 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 5 minutes, 29 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 4 minutes, 54 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 4 minutes, 22 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 3 minutes, 50 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 3 minutes, 18 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 2 minutes, 46 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 2 minutes, 15 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 1 minute, 44 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 1 minute, 13 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 42 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 10 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 5 minutes, 29 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 5 minutes, 2 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 4 minutes, 27 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 3 minutes, 58 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 3 minutes, 28 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 2 minutes, 56 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 2 minutes, 24 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 1 minute, 52 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 20 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 49 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 19 seconds.
20250921 052602	500	13	731	24	5	55071000	20

[mbo] 4: num.trees=500; max.depth=13; min.node.size=731; mtry=24 : y = 5.51e+07 : 1841.4 secs : infill_ei

Saved the current state after iteration 5 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 888 points instead of 1000!”

Growing trees.. Progress: 4%. Estimated remaining time: 12 minutes, 9 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 11 minutes, 20 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 10 minutes, 35 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 9 minutes, 58 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 9 minutes, 13 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 8 minutes, 25 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 7 minutes, 45 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 7 minutes, 9 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 6 minutes, 28 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 5 minutes, 51 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 5 minutes, 13 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 4 minutes, 40 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 4 minutes, 4 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 3 minutes, 31 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 3 minutes, 1 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 2 minutes, 28 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 56 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 1 minute, 22 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 48 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 14 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 10 minutes, 8 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 9 minutes, 23 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 8 minutes, 47 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 8 minutes, 7 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 7 minutes, 38 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 6 minutes, 59 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 6 minutes, 33 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 6 minutes, 0 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 5 minutes, 28 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 4 minutes, 57 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 4 minutes, 26 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 3 minutes, 57 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 3 minutes, 25 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 2 minutes, 55 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 2 minutes, 25 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 56 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 26 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 53 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 20 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 9 minutes, 49 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 9 minutes, 14 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 8 minutes, 44 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 8 minutes, 11 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 7 minutes, 41 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 7 minutes, 8 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 6 minutes, 38 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 6 minutes, 1 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 5 minutes, 26 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 4 minutes, 54 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 4 minutes, 23 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 3 minutes, 48 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 3 minutes, 16 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 2 minutes, 43 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 2 minutes, 10 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 36 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 1 minute, 5 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 33 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 2 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 9 minutes, 25 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 9 minutes, 2 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 8 minutes, 28 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 8 minutes, 3 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 7 minutes, 32 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 7 minutes, 2 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 6 minutes, 32 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 6 minutes, 1 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 5 minutes, 29 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 4 minutes, 57 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 4 minutes, 21 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 3 minutes, 49 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 3 minutes, 14 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 2 minutes, 42 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 2 minutes, 9 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 36 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 1 minute, 4 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 31 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 9 minutes, 20 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 8 minutes, 45 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 8 minutes, 2 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 7 minutes, 30 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 6 minutes, 57 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 6 minutes, 27 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 5 minutes, 53 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 5 minutes, 20 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 4 minutes, 50 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 4 minutes, 20 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 3 minutes, 49 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 3 minutes, 17 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 2 minutes, 45 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 2 minutes, 12 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 39 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 7 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 34 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 3 seconds.
20250921 061828	500	19	1000	33	5	55020000	21

[mbo] 5: num.trees=500; max.depth=19; min.node.size=1000; mtry=33 : y = 5.5e+07 : 3142.9 secs : infill_ei

Saved the current state after iteration 6 in the file HT450.RDATA.

20250921 062033	20	25	550	28	5	50829000	22

[mbo] 6: num.trees=20; max.depth=25; min.node.size=550; mtry=28 : y = 5.08e+07 : 119.8 secs : infill_ei

Growing trees.. Progress: 93%. Estimated remaining time: 2 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 2 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 2 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 1 seconds.
20250921 062359	253	30	711	3	5	53793000	23

[mbo] 7: num.trees=253; max.depth=30; min.node.size=711; mtry=3 : y = 5.38e+07 : 205.8 secs : infill_ei

Growing trees.. Progress: 14%. Estimated remaining time: 3 minutes, 22 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 2 minutes, 41 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 2 minutes, 10 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 1 minute, 36 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 1 minute, 6 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 33 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 3 minutes, 4 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 2 minutes, 35 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 2 minutes, 5 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 1 minute, 32 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 28 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 3 minutes, 4 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 2 minutes, 35 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 2 minutes, 0 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 1 minute, 28 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 57 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 26 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 3 minutes, 15 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 2 minutes, 41 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 2 minutes, 7 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 1 minute, 35 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 1 minute, 3 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 32 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 3 minutes, 15 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 2 minutes, 41 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 2 minutes, 7 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 1 minute, 35 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 1 minute, 4 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 32 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
20250921 064253	139	30	939	41	5	53886000	24

[mbo] 8: num.trees=139; max.depth=30; min.node.size=939; mtry=41 : y = 5.39e+07 : 1133.2 secs : infill_ei

Saved the current state after iteration 9 in the file HT450.RDATA.

20250921 064549	109	26	798	8	5	53577000	25

[mbo] 9: num.trees=109; max.depth=26; min.node.size=798; mtry=8 : y = 5.36e+07 : 173.0 secs : infill_ei

Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 41 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 4 minutes, 14 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 3 minutes, 39 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 3 minutes, 7 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 2 minutes, 35 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 2 minutes, 2 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 59 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 28 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 50 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 4 minutes, 14 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 3 minutes, 43 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 3 minutes, 12 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 2 minutes, 38 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 2 minutes, 6 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 1 minute, 35 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 1 minute, 4 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 32 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 41 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 4 minutes, 7 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 3 minutes, 34 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 3 minutes, 2 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 2 minutes, 30 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 1 minute, 59 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 1 minute, 28 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 57 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 25 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 41 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 4 minutes, 14 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 3 minutes, 41 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 3 minutes, 12 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 2 minutes, 40 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 2 minutes, 8 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 1 minute, 37 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 1 minute, 5 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 35 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 4 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 41 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 4 minutes, 10 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 3 minutes, 36 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 3 minutes, 4 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 2 minutes, 33 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 2 minutes, 2 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 58 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 28 seconds.
20250921 071253	453	14	1000	24	5	54501000	26

[mbo] 10: num.trees=453; max.depth=14; min.node.size=1000; mtry=24 : y = 5.45e+07 : 1624.3 secs : infill_ei

Saved the current state after iteration 11 in the file HT450.RDATA.

Growing trees.. Progress: 6%. Estimated remaining time: 7 minutes, 35 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 6 minutes, 56 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 6 minutes, 26 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 5 minutes, 53 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 5 minutes, 22 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 4 minutes, 50 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 4 minutes, 19 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 3 minutes, 48 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 3 minutes, 15 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 2 minutes, 43 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 2 minutes, 13 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 1 minute, 42 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 11 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 7 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 7 minutes, 49 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 7 minutes, 9 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 6 minutes, 36 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 6 minutes, 3 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 5 minutes, 31 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 4 minutes, 59 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 4 minutes, 29 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 3 minutes, 56 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 3 minutes, 26 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 2 minutes, 54 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 2 minutes, 23 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 52 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 19 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 48 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 16 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 8 minutes, 8 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 7 minutes, 18 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 6 minutes, 45 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 6 minutes, 12 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 5 minutes, 38 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 5 minutes, 6 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 4 minutes, 34 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 4 minutes, 1 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 3 minutes, 30 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 2 minutes, 58 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 2 minutes, 26 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 55 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 23 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 53 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 20 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 7 minutes, 49 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 7 minutes, 10 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 6 minutes, 36 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 6 minutes, 2 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 5 minutes, 32 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 4 minutes, 59 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 4 minutes, 26 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 3 minutes, 54 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 3 minutes, 22 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 2 minutes, 50 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 2 minutes, 17 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 46 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 15 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 43 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 12 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 7 minutes, 35 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 7 minutes, 3 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 6 minutes, 31 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 6 minutes, 2 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 5 minutes, 28 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 4 minutes, 56 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 4 minutes, 25 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 3 minutes, 53 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 3 minutes, 21 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 2 minutes, 49 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 2 minutes, 17 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 46 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 14 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 42 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 10 seconds.
20250921 075452	486	15	1	31	5	52692000	27

[mbo] 11: num.trees=486; max.depth=15; min.node.size=1; mtry=31 : y = 5.27e+07 : 2512.6 secs : infill_ei

Saved the current state after iteration 12 in the file HT450.RDATA.

Growing trees.. Progress: 72%. Estimated remaining time: 11 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 11 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 11 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 11 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 11 seconds.
20250921 075931	417	19	277	2	5	53724000	28

[mbo] 12: num.trees=417; max.depth=19; min.node.size=277; mtry=2 : y = 5.37e+07 : 275.6 secs : infill_ei

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 994 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 815 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 468 points instead of 1000!”

20250921 080248	488	10	1000	2	5	51105000	29

[mbo] 13: num.trees=488; max.depth=10; min.node.size=1000; mtry=2 : y = 5.11e+07 : 196.2 secs : infill_ei

Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 0 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 3 minutes, 29 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 2 minutes, 56 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 2 minutes, 23 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 1 minute, 52 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 1 minute, 21 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 49 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 17 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 54 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 3 minutes, 23 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 2 minutes, 52 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 2 minutes, 21 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 1 minute, 49 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 1 minute, 17 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 46 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 15 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 54 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 3 minutes, 27 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 2 minutes, 54 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 2 minutes, 22 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 1 minute, 49 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 1 minute, 18 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 46 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 14 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 0 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 3 minutes, 29 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 3 minutes, 0 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 2 minutes, 27 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 1 minute, 54 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 1 minute, 23 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 51 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 19 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 54 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 3 minutes, 23 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 2 minutes, 54 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 2 minutes, 24 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 1 minute, 53 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 1 minute, 21 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 51 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 20 seconds.
20250921 082610	420	17	594	19	5	54180000	30

[mbo] 14: num.trees=420; max.depth=17; min.node.size=594; mtry=19 : y = 5.42e+07 : 1400.8 secs : infill_ei

Saved the current state after iteration 15 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 991 points instead of 1000!”

Growing trees.. Progress: 6%. Estimated remaining time: 7 minutes, 48 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 7 minutes, 7 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 6 minutes, 33 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 6 minutes, 4 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 5 minutes, 31 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 4 minutes, 59 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 4 minutes, 29 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 3 minutes, 59 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 3 minutes, 28 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 2 minutes, 56 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 2 minutes, 25 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 54 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 22 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 51 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 18 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 7 minutes, 18 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 6 minutes, 47 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 6 minutes, 16 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 5 minutes, 45 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 5 minutes, 15 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 4 minutes, 42 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 4 minutes, 10 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 3 minutes, 39 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 3 minutes, 7 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 2 minutes, 35 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 2 minutes, 3 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 1 minute, 33 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 1 minute, 1 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 29 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 7 minutes, 18 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 6 minutes, 54 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 6 minutes, 29 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 5 minutes, 54 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 5 minutes, 21 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 4 minutes, 50 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 4 minutes, 20 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 3 minutes, 51 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 3 minutes, 21 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 2 minutes, 51 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 2 minutes, 24 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 2 minutes, 12 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 53 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 36 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 17 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 50 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 16 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 9 minutes, 25 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 9 minutes, 39 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 8 minutes, 41 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 8 minutes, 9 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 7 minutes, 5 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 6 minutes, 14 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 5 minutes, 28 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 4 minutes, 51 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 4 minutes, 11 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 3 minutes, 33 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 2 minutes, 55 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 2 minutes, 19 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 1 minute, 44 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 10 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 35 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 2 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 7 minutes, 32 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 7 minutes, 0 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 6 minutes, 28 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 5 minutes, 53 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 5 minutes, 19 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 4 minutes, 48 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 4 minutes, 18 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 3 minutes, 46 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 3 minutes, 17 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 2 minutes, 48 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 2 minutes, 22 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 53 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 23 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 51 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 20 seconds.
20250921 090936	500	30	765	26	5	54648000	31

[mbo] 15: num.trees=500; max.depth=30; min.node.size=765; mtry=26 : y = 5.46e+07 : 2602.2 secs : infill_ei

Saved the current state after iteration 16 in the file HT450.RDATA.

20250921 091152	472	1	805	33	5	44133000	32

[mbo] 16: num.trees=472; max.depth=1; min.node.size=805; mtry=33 : y = 4.41e+07 : 130.0 secs : infill_ei

Growing trees.. Progress: 9%. Estimated remaining time: 5 minutes, 19 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 4 minutes, 47 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 4 minutes, 13 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 3 minutes, 41 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 3 minutes, 8 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 2 minutes, 37 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 2 minutes, 5 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 1 minute, 32 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 1 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 29 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 5 minutes, 29 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 4 minutes, 53 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 4 minutes, 23 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 3 minutes, 55 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 3 minutes, 24 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 2 minutes, 53 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 2 minutes, 21 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 1 minute, 49 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 1 minute, 15 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 41 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 9 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 5 minutes, 19 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 4 minutes, 47 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 4 minutes, 15 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 3 minutes, 43 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 3 minutes, 11 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 2 minutes, 39 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 2 minutes, 7 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 1 minute, 35 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 3 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 32 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 5 minutes, 29 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 4 minutes, 52 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 4 minutes, 18 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 3 minutes, 43 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 3 minutes, 9 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 2 minutes, 37 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 2 minutes, 5 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 1 minute, 33 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 5 minutes, 29 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 4 minutes, 58 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 4 minutes, 35 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 4 minutes, 27 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 4 minutes, 32 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 4 minutes, 2 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 3 minutes, 23 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 2 minutes, 47 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 2 minutes, 12 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 36 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 1 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 27 seconds.
20250921 094243	373	12	737	36	5	54777000	33

[mbo] 17: num.trees=373; max.depth=12; min.node.size=737; mtry=36 : y = 5.48e+07 : 1851.7 secs : infill_ei

Saved the current state after iteration 18 in the file HT450.RDATA.

Growing trees.. Progress: 7%. Estimated remaining time: 7 minutes, 3 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 6 minutes, 18 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 5 minutes, 53 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 5 minutes, 17 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 4 minutes, 42 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 4 minutes, 11 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 3 minutes, 38 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 3 minutes, 6 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 2 minutes, 34 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 1 minute, 59 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 48 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 15 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 7 minutes, 49 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 7 minutes, 1 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 6 minutes, 28 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 5 minutes, 54 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 5 minutes, 17 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 4 minutes, 44 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 4 minutes, 10 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 3 minutes, 36 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 3 minutes, 1 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 2 minutes, 26 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 1 minute, 49 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 11 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 36 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 13 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 47 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 5 minutes, 6 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 4 minutes, 52 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 4 minutes, 21 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 3 minutes, 48 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 3 minutes, 12 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 2 minutes, 40 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 2 minutes, 7 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 36 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 3 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 32 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 7 minutes, 3 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 6 minutes, 17 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 5 minutes, 36 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 5 minutes, 6 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 4 minutes, 33 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 4 minutes, 0 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 3 minutes, 26 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 2 minutes, 52 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 2 minutes, 19 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 1 minute, 46 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 13 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 38 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 7 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 6 minutes, 37 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 6 minutes, 0 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 5 minutes, 46 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 5 minutes, 23 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 5 minutes, 6 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 4 minutes, 27 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 3 minutes, 49 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 3 minutes, 12 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 2 minutes, 37 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 2 minutes, 2 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 1 minute, 27 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 54 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 22 seconds.
20250921 101955	235	18	877	49	5	54027000	34

[mbo] 18: num.trees=235; max.depth=18; min.node.size=877; mtry=49 : y = 5.4e+07 : 2227.8 secs : infill_ei

Saved the current state after iteration 19 in the file HT450.RDATA.

20250921 102210	158	28	213	2	5	52929000	35

[mbo] 19: num.trees=158; max.depth=28; min.node.size=213; mtry=2 : y = 5.29e+07 : 130.5 secs : infill_ei

Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 6 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 35 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 5 minutes, 0 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 4 minutes, 32 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 4 minutes, 3 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 3 minutes, 30 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 2 minutes, 57 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 2 minutes, 25 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 1 minute, 53 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 1 minute, 21 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 50 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 18 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 5 minutes, 56 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 25 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 4 minutes, 57 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 4 minutes, 25 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 3 minutes, 53 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 3 minutes, 22 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 2 minutes, 51 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 2 minutes, 20 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 1 minute, 48 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 1 minute, 17 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 47 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 16 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 5 minutes, 56 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 21 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 4 minutes, 48 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 4 minutes, 17 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 3 minutes, 45 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 3 minutes, 13 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 2 minutes, 41 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 2 minutes, 10 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 1 minute, 39 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 7 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 35 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 3 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 5 minutes, 47 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 21 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 4 minutes, 48 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 4 minutes, 18 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 3 minutes, 45 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 3 minutes, 15 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 2 minutes, 43 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 2 minutes, 12 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 1 minute, 40 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 8 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 36 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 4 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 6 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 5 minutes, 40 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 5 minutes, 7 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 4 minutes, 35 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 4 minutes, 3 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 3 minutes, 30 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 2 minutes, 57 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 2 minutes, 23 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 1 minute, 48 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 1 minute, 15 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 43 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 10 seconds.
20250921 105550	500	20	787	21	5	54819000	36

[mbo] 20: num.trees=500; max.depth=20; min.node.size=787; mtry=21 : y = 5.48e+07 : 2019.3 secs : infill_ei

Saved the current state after iteration 21 in the file HT450.RDATA.

Growing trees.. Progress: 25%. Estimated remaining time: 1 minute, 31 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 58 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 26 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 53 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 22 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 1 minute, 33 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 31 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 1 minute, 33 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 1 minute, 1 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 29 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 1 minute, 31 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 1 minute, 0 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 28 seconds.
20250921 110650	372	12	438	11	5	55032000	37

[mbo] 21: num.trees=372; max.depth=12; min.node.size=438; mtry=11 : y = 5.5e+07 : 653.8 secs : infill_ei

Saved the current state after iteration 22 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 432 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 982 points instead of 1000!”

Growing trees.. Progress: 9%. Estimated remaining time: 5 minutes, 13 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 4 minutes, 38 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 4 minutes, 3 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 3 minutes, 34 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 3 minutes, 0 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 2 minutes, 28 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 1 minute, 56 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 53 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 21 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 39 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 4 minutes, 8 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 3 minutes, 39 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 3 minutes, 9 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 2 minutes, 40 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 2 minutes, 19 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 2 minutes, 7 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 1 minute, 51 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 32 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 5 minutes, 29 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 4 minutes, 59 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 4 minutes, 24 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 3 minutes, 54 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 3 minutes, 21 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 2 minutes, 48 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 2 minutes, 17 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 1 minute, 45 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 1 minute, 13 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 8 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 5 minutes, 15 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 4 minutes, 39 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 4 minutes, 6 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 3 minutes, 38 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 3 minutes, 8 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 2 minutes, 36 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 2 minutes, 2 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 0 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 28 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 5 minutes, 29 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 4 minutes, 50 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 4 minutes, 19 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 3 minutes, 45 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 3 minutes, 13 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 2 minutes, 39 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 2 minutes, 5 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 1 minute, 32 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 1 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 28 seconds.
20250921 113728	500	27	1000	18	5	54849000	38

[mbo] 22: num.trees=500; max.depth=27; min.node.size=1000; mtry=18 : y = 5.48e+07 : 1833.0 secs : infill_ei

Saved the current state after iteration 23 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 987 points instead of 1000!”

Growing trees.. Progress: 19%. Estimated remaining time: 2 minutes, 8 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 1 minute, 35 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 1 minute, 4 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 2 minutes, 0 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 1 minute, 32 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 2 minutes, 12 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 1 minute, 36 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 1 minute, 4 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 2 minutes, 8 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 1 minute, 36 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 1 minute, 1 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 28 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 2 minutes, 4 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 57 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 26 seconds.
20250921 115104	190	27	1000	21	5	54279000	39

[mbo] 23: num.trees=190; max.depth=27; min.node.size=1000; mtry=21 : y = 5.43e+07 : 810.3 secs : infill_ei

Saved the current state after iteration 24 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 984 points instead of 1000!”

Growing trees.. Progress: 3%. Estimated remaining time: 14 minutes, 40 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 13 minutes, 56 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 13 minutes, 29 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 13 minutes, 5 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 12 minutes, 32 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 12 minutes, 3 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 11 minutes, 27 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 10 minutes, 54 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 10 minutes, 19 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 9 minutes, 46 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 9 minutes, 12 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 8 minutes, 34 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 8 minutes, 0 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 7 minutes, 26 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 6 minutes, 50 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 6 minutes, 18 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 5 minutes, 48 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 5 minutes, 16 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 4 minutes, 43 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 4 minutes, 11 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 3 minutes, 39 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 3 minutes, 6 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 2 minutes, 34 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 2 minutes, 2 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 1 minute, 29 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 57 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 26 seconds.
Growing trees.. Progress: 3%. Estimated remaining time: 15 minutes, 9 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 14 minutes, 10 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 13 minutes, 21 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 12 minutes, 47 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 12 minutes, 14 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 11 minutes, 37 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 11 minutes, 13 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 10 minutes, 40 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 10 minutes, 9 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 9 minutes, 38 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 9 minutes, 10 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 8 minutes, 38 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 8 minutes, 6 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 7 minutes, 35 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 7 minutes, 8 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 6 minutes, 41 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 6 minutes, 14 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 5 minutes, 59 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 5 minutes, 48 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 5 minutes, 35 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 5 minutes, 15 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 4 minutes, 49 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 4 minutes, 14 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 3 minutes, 39 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 3 minutes, 7 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 2 minutes, 35 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 59 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 1 minute, 23 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 47 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 11 seconds.
Growing trees.. Progress: 3%. Estimated remaining time: 15 minutes, 9 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 14 minutes, 23 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 13 minutes, 47 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 13 minutes, 6 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 12 minutes, 29 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 11 minutes, 58 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 11 minutes, 26 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 10 minutes, 54 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 10 minutes, 23 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 9 minutes, 54 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 9 minutes, 24 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 8 minutes, 56 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 8 minutes, 23 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 7 minutes, 50 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 7 minutes, 17 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 6 minutes, 44 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 6 minutes, 11 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 5 minutes, 38 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 5 minutes, 5 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 4 minutes, 31 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 4 minutes, 0 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 3 minutes, 26 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 2 minutes, 53 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 2 minutes, 20 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 47 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 1 minute, 15 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 46 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 14 seconds.
Growing trees.. Progress: 3%. Estimated remaining time: 15 minutes, 37 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 14 minutes, 23 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 13 minutes, 55 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 13 minutes, 25 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 12 minutes, 55 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 12 minutes, 18 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 11 minutes, 44 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 11 minutes, 16 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 10 minutes, 43 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 10 minutes, 10 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 9 minutes, 35 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 9 minutes, 5 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 8 minutes, 32 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 8 minutes, 2 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 7 minutes, 27 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 6 minutes, 55 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 6 minutes, 21 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 5 minutes, 47 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 5 minutes, 13 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 4 minutes, 39 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 4 minutes, 7 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 3 minutes, 36 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 3 minutes, 2 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 2 minutes, 29 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 55 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 1 minute, 21 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 50 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 18 seconds.
Growing trees.. Progress: 3%. Estimated remaining time: 15 minutes, 9 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 14 minutes, 36 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 13 minutes, 46 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 13 minutes, 11 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 12 minutes, 41 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 12 minutes, 7 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 11 minutes, 39 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 11 minutes, 5 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 10 minutes, 32 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 10 minutes, 10 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 9 minutes, 37 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 9 minutes, 4 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 8 minutes, 30 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 7 minutes, 57 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 7 minutes, 23 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 6 minutes, 51 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 6 minutes, 22 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 5 minutes, 50 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 5 minutes, 18 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 4 minutes, 46 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 4 minutes, 14 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 3 minutes, 40 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 3 minutes, 6 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 2 minutes, 32 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 1 minute, 58 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 1 minute, 24 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 50 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 18 seconds.
20250921 131040	500	17	814	50	5	54279000	40

[mbo] 24: num.trees=500; max.depth=17; min.node.size=814; mtry=50 : y = 5.43e+07 : 4772.7 secs : infill_ei

Saved the current state after iteration 25 in the file HT450.RDATA.

Growing trees.. Progress: 11%. Estimated remaining time: 3 minutes, 59 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 3 minutes, 29 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 3 minutes, 2 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 2 minutes, 33 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 2 minutes, 2 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 1 minute, 31 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 0 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 29 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 3 minutes, 59 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 3 minutes, 23 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 2 minutes, 54 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 2 minutes, 21 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 1 minute, 48 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 1 minute, 18 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 49 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 18 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 54 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 3 minutes, 20 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 2 minutes, 48 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 2 minutes, 19 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 1 minute, 48 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 1 minute, 15 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 43 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 12 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 44 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 3 minutes, 13 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 2 minutes, 42 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 2 minutes, 10 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 1 minute, 38 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 1 minute, 7 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 37 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 5 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 3 minutes, 59 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 3 minutes, 23 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 2 minutes, 50 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 2 minutes, 20 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 1 minute, 48 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 1 minute, 15 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 43 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 11 seconds.
20250921 133415	462	26	365	14	5	54042000	41

[mbo] 25: num.trees=462; max.depth=26; min.node.size=365; mtry=14 : y = 5.4e+07 : 1409.4 secs : infill_ei

Saved the current state after iteration 26 in the file HT450.RDATA.

Growing trees.. Progress: 17%. Estimated remaining time: 2 minutes, 35 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 2 minutes, 3 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 1 minute, 1 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 2 minutes, 40 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 2 minutes, 8 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 1 minute, 32 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 58 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 27 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 39 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 2 minutes, 6 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 1 minute, 33 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 58 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 25 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 2 minutes, 35 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 1 minute, 59 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 20 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 2 minutes, 22 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 1 minute, 53 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 1 minute, 21 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 50 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 18 seconds.
20250921 135008	123	15	1000	45	5	53994000	42

[mbo] 26: num.trees=123; max.depth=15; min.node.size=1000; mtry=45 : y = 5.4e+07 : 947.5 secs : infill_ei

Saved the current state after iteration 27 in the file HT450.RDATA.

Growing trees.. Progress: 39%. Estimated remaining time: 49 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 18 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 51 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 19 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 49 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 18 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 50 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 18 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 49 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 17 seconds.
20250921 135729	174	15	353	14	5	54273000	43

[mbo] 27: num.trees=174; max.depth=15; min.node.size=353; mtry=14 : y = 5.43e+07 : 434.7 secs : infill_ei

Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 4 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 3 minutes, 37 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 3 minutes, 2 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 2 minutes, 31 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 2 minutes, 0 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 1 minute, 29 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 58 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 27 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 17 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 3 minutes, 46 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 3 minutes, 15 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 2 minutes, 42 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 2 minutes, 10 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 1 minute, 37 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 6 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 34 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 3 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 4 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 3 minutes, 37 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 3 minutes, 4 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 2 minutes, 32 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 2 minutes, 2 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 1 minute, 32 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 1 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 17 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 3 minutes, 46 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 3 minutes, 12 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 2 minutes, 40 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 2 minutes, 8 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 1 minute, 35 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 3 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 31 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 4 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 3 minutes, 33 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 3 minutes, 2 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 2 minutes, 31 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 2 minutes, 0 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 1 minute, 29 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 58 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 26 seconds.
20250921 142148	409	12	727	26	5	55035000	44

[mbo] 28: num.trees=409; max.depth=12; min.node.size=727; mtry=26 : y = 5.5e+07 : 1458.6 secs : infill_ei

Saved the current state after iteration 29 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 827 points instead of 1000!”

Growing trees.. Progress: 89%. Estimated remaining time: 3 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 4 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 3 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 3 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 4 seconds.
20250921 142542	500	11	322	2	5	52518000	45

[mbo] 29: num.trees=500; max.depth=11; min.node.size=322; mtry=2 : y = 5.25e+07 : 229.5 secs : infill_ei

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 496 points instead of 1000!”

Growing trees.. Progress: 6%. Estimated remaining time: 8 minutes, 42 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 8 minutes, 11 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 7 minutes, 37 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 7 minutes, 3 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 6 minutes, 29 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 5 minutes, 59 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 5 minutes, 30 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 4 minutes, 59 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 4 minutes, 29 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 3 minutes, 58 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 3 minutes, 27 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 2 minutes, 56 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 2 minutes, 25 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 1 minute, 53 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 21 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 49 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 17 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 9 minutes, 3 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 8 minutes, 11 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 7 minutes, 43 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 7 minutes, 5 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 6 minutes, 29 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 5 minutes, 55 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 5 minutes, 27 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 4 minutes, 55 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 4 minutes, 23 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 3 minutes, 54 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 3 minutes, 24 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 2 minutes, 53 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 2 minutes, 21 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 1 minute, 50 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 18 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 46 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 15 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 8 minutes, 42 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 8 minutes, 19 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 7 minutes, 50 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 7 minutes, 11 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 6 minutes, 43 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 6 minutes, 8 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 5 minutes, 38 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 5 minutes, 5 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 4 minutes, 31 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 3 minutes, 58 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 3 minutes, 26 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 2 minutes, 53 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 2 minutes, 22 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 1 minute, 50 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 18 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 46 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 14 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 9 minutes, 3 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 8 minutes, 19 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 7 minutes, 45 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 7 minutes, 10 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 6 minutes, 34 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 6 minutes, 5 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 5 minutes, 31 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 4 minutes, 59 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 4 minutes, 29 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 3 minutes, 58 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 3 minutes, 25 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 2 minutes, 55 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 2 minutes, 24 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 1 minute, 53 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 22 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 21 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 9 minutes, 3 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 8 minutes, 21 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 7 minutes, 50 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 7 minutes, 11 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 6 minutes, 38 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 6 minutes, 4 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 5 minutes, 30 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 4 minutes, 58 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 4 minutes, 27 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 3 minutes, 54 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 3 minutes, 22 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 2 minutes, 50 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 2 minutes, 18 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 1 minute, 47 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 17 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 44 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 12 seconds.
20250921 151301	500	15	806	35	5	54960000	46

[mbo] 30: num.trees=500; max.depth=15; min.node.size=806; mtry=35 : y = 5.5e+07 : 2838.6 secs : infill_ei

Saved the current state after iteration 31 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 448 points instead of 1000!”

Growing trees.. Progress: 24%. Estimated remaining time: 1 minute, 40 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 1 minute, 11 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 8 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 1 minute, 44 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 1 minute, 13 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 43 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 11 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 1 minute, 41 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 1 minute, 8 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 37 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 5 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 1 minute, 48 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 1 minute, 16 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 44 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 13 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 1 minute, 52 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 1 minute, 20 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 48 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 16 seconds.
20250921 152506	162	30	448	21	5	54684000	47

[mbo] 31: num.trees=162; max.depth=30; min.node.size=448; mtry=21 : y = 5.47e+07 : 721.4 secs : infill_ei

Saved the current state after iteration 32 in the file HT450.RDATA.

Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 6 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 29 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 4 minutes, 49 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 4 minutes, 16 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 3 minutes, 43 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 3 minutes, 13 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 2 minutes, 42 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 2 minutes, 9 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 1 minute, 37 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 5 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 35 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 4 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 5 minutes, 46 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 5 minutes, 14 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 4 minutes, 45 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 4 minutes, 13 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 3 minutes, 40 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 3 minutes, 7 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 2 minutes, 35 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 2 minutes, 3 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 1 minute, 31 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 59 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 26 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 5 minutes, 26 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 5 minutes, 4 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 4 minutes, 33 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 4 minutes, 3 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 3 minutes, 32 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 2 minutes, 59 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 2 minutes, 26 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 1 minute, 54 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 22 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 50 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 18 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 5 minutes, 35 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 5 minutes, 4 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 4 minutes, 33 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 4 minutes, 4 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 3 minutes, 32 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 3 minutes, 0 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 2 minutes, 28 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 1 minute, 58 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 54 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 24 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 17 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 45 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 5 minutes, 6 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 4 minutes, 29 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 3 minutes, 53 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 3 minutes, 19 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 2 minutes, 46 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 2 minutes, 13 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 1 minute, 38 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 5 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 33 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
20250921 155738	461	28	662	21	5	53865000	48

[mbo] 32: num.trees=461; max.depth=28; min.node.size=662; mtry=21 : y = 5.39e+07 : 1948.0 secs : infill_ei

Saved the current state after iteration 33 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 112 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 969 points instead of 1000!”

Growing trees.. Progress: 58%. Estimated remaining time: 22 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 20 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 22 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 21 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 21 seconds.
20250921 160319	500	30	1000	2	5	53286000	49

[mbo] 33: num.trees=500; max.depth=30; min.node.size=1000; mtry=2 : y = 5.33e+07 : 337.2 secs : infill_ei

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 862 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 720 points instead of 1000!”

Growing trees.. Progress: 6%. Estimated remaining time: 8 minutes, 23 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 7 minutes, 52 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 7 minutes, 15 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 6 minutes, 37 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 6 minutes, 7 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 5 minutes, 35 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 5 minutes, 3 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 4 minutes, 30 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 3 minutes, 58 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 3 minutes, 25 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 2 minutes, 54 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 2 minutes, 21 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 1 minute, 50 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 21 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 48 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 17 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 8 minutes, 4 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 7 minutes, 32 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 7 minutes, 0 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 6 minutes, 32 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 6 minutes, 6 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 5 minutes, 35 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 5 minutes, 4 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 4 minutes, 32 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 4 minutes, 1 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 3 minutes, 29 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 2 minutes, 57 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 2 minutes, 25 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 53 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 22 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 50 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 18 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 8 minutes, 23 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 7 minutes, 52 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 7 minutes, 20 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 6 minutes, 47 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 6 minutes, 13 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 5 minutes, 44 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 5 minutes, 12 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 4 minutes, 39 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 4 minutes, 7 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 3 minutes, 35 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 3 minutes, 3 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 2 minutes, 29 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 57 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 21 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 8 minutes, 23 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 7 minutes, 49 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 7 minutes, 11 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 6 minutes, 42 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 6 minutes, 12 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 5 minutes, 38 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 5 minutes, 10 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 4 minutes, 39 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 4 minutes, 6 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 3 minutes, 34 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 3 minutes, 2 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 2 minutes, 31 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 2 minutes, 1 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 29 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 56 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 23 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 8 minutes, 21 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 7 minutes, 47 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 7 minutes, 15 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 6 minutes, 40 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 6 minutes, 9 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 5 minutes, 38 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 5 minutes, 8 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 4 minutes, 37 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 4 minutes, 6 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 3 minutes, 36 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 3 minutes, 4 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 2 minutes, 31 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 59 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 27 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 55 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 23 seconds.
20250921 164836	500	25	903	28	5	55095000	50

[mbo] 34: num.trees=500; max.depth=25; min.node.size=903; mtry=28 : y = 5.51e+07 : 2717.2 secs : infill_ei

Saved the current state after iteration 35 in the file HT450.RDATA.

Growing trees.. Progress: 24%. Estimated remaining time: 1 minute, 37 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 1 minute, 5 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 34 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 2 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 1 minute, 38 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 1 minute, 6 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 35 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 4 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 1 minute, 40 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 1 minute, 7 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 36 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 4 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 1 minute, 33 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 31 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 1 minute, 37 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 1 minute, 6 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 35 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 3 seconds.
20250921 170002	318	11	814	16	5	54033000	51

[mbo] 35: num.trees=318; max.depth=11; min.node.size=814; mtry=16 : y = 5.4e+07 : 679.2 secs : infill_ei

Saved the current state after iteration 36 in the file HT450.RDATA.

Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 54 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 4 minutes, 7 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 3 minutes, 37 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 3 minutes, 1 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 2 minutes, 30 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 1 minute, 58 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 1 minute, 24 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 50 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 16 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 45 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 4 minutes, 7 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 3 minutes, 32 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 2 minutes, 58 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 2 minutes, 24 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 1 minute, 50 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 1 minute, 17 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 47 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 14 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 36 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 4 minutes, 5 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 3 minutes, 30 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 2 minutes, 55 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 2 minutes, 25 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 1 minute, 53 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 1 minute, 21 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 48 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 16 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 54 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 4 minutes, 7 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 3 minutes, 34 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 3 minutes, 0 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 2 minutes, 29 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 1 minute, 57 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 1 minute, 23 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 50 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 16 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 36 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 4 minutes, 3 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 3 minutes, 28 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 2 minutes, 58 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 2 minutes, 26 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 1 minute, 53 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 1 minute, 20 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 47 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 14 seconds.
20250921 172626	149	23	418	50	5	51549000	52

[mbo] 36: num.trees=149; max.depth=23; min.node.size=418; mtry=50 : y = 5.15e+07 : 1578.3 secs : infill_ei

Saved the current state after iteration 37 in the file HT450.RDATA.

Growing trees.. Progress: 44%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 7 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 38 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 7 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 38 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 7 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 38 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 7 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 8 seconds.
20250921 173249	135	19	883	15	5	54696000	53

[mbo] 37: num.trees=135; max.depth=19; min.node.size=883; mtry=15 : y = 5.47e+07 : 378.4 secs : infill_ei

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 540 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 916 points instead of 1000!”

20250921 173350	78	18	404	2	5	52389000	54

[mbo] 38: num.trees=78; max.depth=18; min.node.size=404; mtry=2 : y = 5.24e+07 : 60.1 secs : infill_ei

Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 44 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 2 minutes, 10 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 1 minute, 39 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 1 minute, 7 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 35 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 2 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 44 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 2 minutes, 10 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 1 minute, 38 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 1 minute, 7 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 35 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 3 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 44 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 2 minutes, 10 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 1 minute, 38 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 1 minute, 6 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 35 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 3 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 44 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 2 minutes, 12 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 1 minute, 41 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 37 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 4 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 44 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 2 minutes, 12 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 1 minute, 38 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 1 minute, 7 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 35 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 3 seconds.
20250921 175025	158	18	880	35	5	53991000	55

[mbo] 39: num.trees=158; max.depth=18; min.node.size=880; mtry=35 : y = 5.4e+07 : 995.6 secs : infill_ei

Saved the current state after iteration 40 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 528 points instead of 1000!”

Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 5 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 3 minutes, 31 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 2 minutes, 59 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 2 minutes, 27 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 1 minute, 55 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 1 minute, 22 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 21 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 5 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 3 minutes, 31 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 2 minutes, 59 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 2 minutes, 27 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 1 minute, 56 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 1 minute, 26 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 53 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 23 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 5 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 3 minutes, 35 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 3 minutes, 3 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 2 minutes, 30 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 1 minute, 57 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 1 minute, 24 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 51 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 19 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 12 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 3 minutes, 44 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 3 minutes, 12 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 2 minutes, 39 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 2 minutes, 7 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 1 minute, 35 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 4 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 33 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 5 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 3 minutes, 41 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 3 minutes, 10 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 2 minutes, 35 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 2 minutes, 2 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 1 minute, 31 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 1 minute, 0 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 27 seconds.
20250921 181413	384	10	502	34	5	54579000	56

[mbo] 40: num.trees=384; max.depth=10; min.node.size=502; mtry=34 : y = 5.46e+07 : 1422.0 secs : infill_ei

Saved the current state after iteration 41 in the file HT450.RDATA.

Growing trees.. Progress: 19%. Estimated remaining time: 2 minutes, 14 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 1 minute, 43 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 1 minute, 12 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 41 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 9 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 2 minutes, 14 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 1 minute, 42 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 1 minute, 11 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 8 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 2 minutes, 10 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 1 minute, 39 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 37 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 6 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 2 minutes, 14 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 1 minute, 40 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 38 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 6 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 2 minutes, 16 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 1 minute, 45 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 1 minute, 14 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 43 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 11 seconds.
20250921 182853	401	13	634	14	5	54087000	57

[mbo] 41: num.trees=401; max.depth=13; min.node.size=634; mtry=14 : y = 5.41e+07 : 876.0 secs : infill_ei

Saved the current state after iteration 42 in the file HT450.RDATA.

Growing trees.. Progress: 31%. Estimated remaining time: 1 minute, 8 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 37 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 6 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 1 minute, 8 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 36 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 6 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 1 minute, 10 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 38 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 6 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 1 minute, 6 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 34 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 3 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 1 minute, 10 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 37 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 6 seconds.
20250921 183757	376	10	219	11	5	55158000	58

[mbo] 42: num.trees=376; max.depth=10; min.node.size=219; mtry=11 : y = 5.52e+07 : 537.7 secs : infill_ei

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 999 points instead of 1000!”

Growing trees.. Progress: 7%. Estimated remaining time: 7 minutes, 4 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 6 minutes, 33 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 6 minutes, 2 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 5 minutes, 30 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 4 minutes, 59 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 4 minutes, 29 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 3 minutes, 56 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 3 minutes, 22 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 2 minutes, 51 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 2 minutes, 20 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 1 minute, 49 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 17 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 45 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 14 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 7 minutes, 4 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 6 minutes, 33 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 6 minutes, 2 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 5 minutes, 31 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 5 minutes, 0 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 4 minutes, 26 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 3 minutes, 54 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 3 minutes, 22 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 2 minutes, 52 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 2 minutes, 20 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 1 minute, 48 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 17 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 44 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 13 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 7 minutes, 4 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 6 minutes, 27 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 6 minutes, 2 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 5 minutes, 31 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 4 minutes, 59 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 4 minutes, 28 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 3 minutes, 56 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 3 minutes, 24 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 2 minutes, 51 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 2 minutes, 20 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 1 minute, 47 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 15 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 44 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 13 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 7 minutes, 4 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 6 minutes, 33 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 6 minutes, 6 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 5 minutes, 34 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 5 minutes, 2 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 4 minutes, 33 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 4 minutes, 1 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 3 minutes, 31 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 2 minutes, 58 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 2 minutes, 27 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 1 minute, 54 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 23 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 50 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 18 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 7 minutes, 18 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 6 minutes, 40 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 6 minutes, 11 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 5 minutes, 37 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 5 minutes, 2 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 4 minutes, 34 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 4 minutes, 2 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 3 minutes, 28 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 2 minutes, 57 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 2 minutes, 26 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 1 minute, 55 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 24 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 51 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 19 seconds.
20250921 191718	500	17	944	27	5	54783000	59

[mbo] 43: num.trees=500; max.depth=17; min.node.size=944; mtry=27 : y = 5.48e+07 : 2361.0 secs : infill_ei

Saved the current state after iteration 44 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 500 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 360 points instead of 1000!”

Growing trees.. Progress: 11%. Estimated remaining time: 3 minutes, 59 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 3 minutes, 28 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 2 minutes, 55 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 2 minutes, 23 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 1 minute, 51 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 1 minute, 21 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 49 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 18 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 4 minutes, 1 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 3 minutes, 26 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 2 minutes, 55 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 2 minutes, 24 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 1 minute, 53 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 1 minute, 23 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 21 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 4 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 3 minutes, 36 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 3 minutes, 4 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 2 minutes, 31 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 1 minute, 58 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 1 minute, 26 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 55 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 25 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 15 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 3 minutes, 38 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 3 minutes, 7 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 2 minutes, 34 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 2 minutes, 2 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 58 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 27 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 4 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 3 minutes, 30 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 3 minutes, 0 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 2 minutes, 28 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 1 minute, 56 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 1 minute, 24 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 21 seconds.
20250921 194101	453	11	455	25	5	54645000	60

[mbo] 44: num.trees=453; max.depth=11; min.node.size=455; mtry=25 : y = 5.46e+07 : 1418.0 secs : infill_ei

Saved the current state after iteration 45 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 270 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 176 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 192 points instead of 1000!”

Growing trees.. Progress: 3%. Estimated remaining time: 17 minutes, 14 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 16 minutes, 8 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 15 minutes, 25 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 14 minutes, 47 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 14 minutes, 12 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 13 minutes, 34 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 13 minutes, 1 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 12 minutes, 28 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 11 minutes, 56 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 11 minutes, 24 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 10 minutes, 53 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 10 minutes, 24 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 9 minutes, 53 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 9 minutes, 21 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 8 minutes, 47 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 8 minutes, 10 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 7 minutes, 37 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 7 minutes, 6 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 6 minutes, 30 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 5 minutes, 59 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 5 minutes, 27 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 4 minutes, 55 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 4 minutes, 23 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 3 minutes, 51 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 3 minutes, 21 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 2 minutes, 49 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 2 minutes, 15 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 1 minute, 41 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 33 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 3%. Estimated remaining time: 16 minutes, 8 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 14 minutes, 50 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 14 minutes, 5 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 13 minutes, 32 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 12 minutes, 53 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 12 minutes, 27 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 11 minutes, 52 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 11 minutes, 19 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 10 minutes, 41 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 10 minutes, 7 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 9 minutes, 34 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 9 minutes, 0 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 8 minutes, 29 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 7 minutes, 56 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 7 minutes, 25 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 6 minutes, 55 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 6 minutes, 22 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 5 minutes, 47 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 5 minutes, 16 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 4 minutes, 43 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 4 minutes, 9 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 3 minutes, 37 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 3 minutes, 3 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 2 minutes, 32 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 2 minutes, 2 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 1 minute, 29 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 57 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 26 seconds.
Growing trees.. Progress: 3%. Estimated remaining time: 14 minutes, 40 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 14 minutes, 23 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 14 minutes, 5 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 13 minutes, 25 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 12 minutes, 49 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 12 minutes, 14 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 11 minutes, 47 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 11 minutes, 16 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 10 minutes, 47 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 10 minutes, 15 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 9 minutes, 44 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 9 minutes, 10 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 8 minutes, 34 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 8 minutes, 0 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 7 minutes, 25 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 6 minutes, 52 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 6 minutes, 20 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 5 minutes, 48 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 5 minutes, 17 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 4 minutes, 45 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 4 minutes, 11 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 3 minutes, 37 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 3 minutes, 6 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 2 minutes, 32 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 1 minute, 58 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 20 seconds.
Growing trees.. Progress: 3%. Estimated remaining time: 15 minutes, 37 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 14 minutes, 50 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 14 minutes, 12 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 13 minutes, 45 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 13 minutes, 6 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 12 minutes, 40 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 12 minutes, 5 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 11 minutes, 38 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 11 minutes, 0 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 10 minutes, 25 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 9 minutes, 52 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 9 minutes, 20 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 8 minutes, 47 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 8 minutes, 16 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 7 minutes, 42 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 7 minutes, 11 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 6 minutes, 41 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 6 minutes, 7 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 5 minutes, 31 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 4 minutes, 59 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 4 minutes, 29 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 3 minutes, 56 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 3 minutes, 22 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 2 minutes, 49 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 2 minutes, 16 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 1 minute, 42 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 1 minute, 10 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 37 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 5 seconds.
Growing trees.. Progress: 3%. Estimated remaining time: 16 minutes, 42 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 15 minutes, 21 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 15 minutes, 4 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 14 minutes, 1 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 13 minutes, 18 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 12 minutes, 44 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 12 minutes, 21 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 11 minutes, 43 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 11 minutes, 12 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 10 minutes, 36 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 10 minutes, 4 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 9 minutes, 31 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 9 minutes, 2 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 8 minutes, 33 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 8 minutes, 1 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 7 minutes, 30 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 6 minutes, 59 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 6 minutes, 24 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 5 minutes, 49 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 5 minutes, 16 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 4 minutes, 43 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 4 minutes, 10 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 3 minutes, 38 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 3 minutes, 5 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 2 minutes, 33 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 2 minutes, 0 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 1 minute, 28 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 53 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 21 seconds.
20250921 210146	500	30	1000	49	5	53874000	61

[mbo] 45: num.trees=500; max.depth=30; min.node.size=1000; mtry=49 : y = 5.39e+07 : 4837.8 secs : infill_ei

Saved the current state after iteration 46 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 918 points instead of 1000!”

Growing trees.. Progress: 6%. Estimated remaining time: 8 minutes, 9 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 7 minutes, 39 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 7 minutes, 1 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 6 minutes, 30 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 5 minutes, 57 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 5 minutes, 23 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 4 minutes, 47 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 4 minutes, 15 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 3 minutes, 40 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 3 minutes, 8 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 2 minutes, 36 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 2 minutes, 3 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 31 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 59 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 27 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 7 minutes, 54 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 7 minutes, 23 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 6 minutes, 51 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 6 minutes, 19 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 5 minutes, 49 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 5 minutes, 14 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 4 minutes, 41 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 4 minutes, 9 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 3 minutes, 39 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 3 minutes, 7 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 2 minutes, 35 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 2 minutes, 3 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 32 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 0 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 29 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 7 minutes, 54 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 7 minutes, 23 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 6 minutes, 46 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 6 minutes, 17 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 5 minutes, 42 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 5 minutes, 12 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 4 minutes, 41 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 4 minutes, 7 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 3 minutes, 35 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 3 minutes, 5 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 2 minutes, 34 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 2 minutes, 2 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 58 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 27 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 7 minutes, 54 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 7 minutes, 23 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 6 minutes, 52 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 6 minutes, 23 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 5 minutes, 50 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 5 minutes, 16 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 4 minutes, 46 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 4 minutes, 14 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 3 minutes, 43 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 3 minutes, 10 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 2 minutes, 39 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 2 minutes, 8 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 1 minute, 36 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 3 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 31 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 8 minutes, 9 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 7 minutes, 29 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 6 minutes, 54 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 6 minutes, 20 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 5 minutes, 47 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 5 minutes, 15 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 4 minutes, 42 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 4 minutes, 10 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 3 minutes, 37 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 3 minutes, 9 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 2 minutes, 36 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 2 minutes, 4 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 32 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 0 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 27 seconds.
20250921 214459	473	19	733	30	5	53655000	62

[mbo] 46: num.trees=473; max.depth=19; min.node.size=733; mtry=30 : y = 5.37e+07 : 2589.3 secs : infill_ei

Saved the current state after iteration 47 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 600 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 630 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 630 points instead of 1000!”

Growing trees.. Progress: 9%. Estimated remaining time: 4 minutes, 58 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 4 minutes, 24 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 3 minutes, 54 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 3 minutes, 23 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 2 minutes, 50 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 2 minutes, 18 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 1 minute, 46 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 15 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 44 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 13 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 4 minutes, 58 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 4 minutes, 21 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 3 minutes, 45 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 3 minutes, 12 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 2 minutes, 40 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 2 minutes, 10 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 1 minute, 39 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 1 minute, 7 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 35 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 3 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 51 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 4 minutes, 18 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 3 minutes, 45 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 3 minutes, 13 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 2 minutes, 42 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 2 minutes, 10 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 1 minute, 38 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 1 minute, 8 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 37 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 6 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 51 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 4 minutes, 27 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 3 minutes, 56 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 3 minutes, 23 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 2 minutes, 52 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 2 minutes, 21 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 1 minute, 49 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 1 minute, 17 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 45 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 13 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 4 minutes, 58 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 4 minutes, 24 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 3 minutes, 54 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 3 minutes, 27 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 2 minutes, 55 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 2 minutes, 24 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 1 minute, 53 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 1 minute, 21 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 49 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 17 seconds.
20250921 221317	500	22	1000	19	5	54510000	63

[mbo] 47: num.trees=500; max.depth=22; min.node.size=1000; mtry=19 : y = 5.45e+07 : 1693.8 secs : infill_ei

Saved the current state after iteration 48 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 997 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 859 points instead of 1000!”

Growing trees.. Progress: 30%. Estimated remaining time: 1 minute, 10 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 7 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 1 minute, 7 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 35 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 4 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 1 minute, 5 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 35 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 4 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 1 minute, 8 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 37 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 6 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 1 minute, 10 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 7 seconds.
20250921 222246	486	20	1000	6	5	53991000	64

[mbo] 48: num.trees=486; max.depth=20; min.node.size=1000; mtry=6 : y = 5.4e+07 : 562.3 secs : infill_ei

Growing trees.. Progress: 17%. Estimated remaining time: 2 minutes, 30 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 1 minute, 59 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 1 minute, 29 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 57 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 26 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 2 minutes, 30 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 2 minutes, 1 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 58 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 26 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 2 minutes, 30 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 2 minutes, 0 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 58 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 27 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 2 minutes, 36 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 2 minutes, 2 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 58 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 26 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 2 minutes, 30 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 1 minute, 59 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 1 minute, 27 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 55 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 25 seconds.
20250921 223844	357	11	320	21	5	53907000	65

[mbo] 49: num.trees=357; max.depth=11; min.node.size=320; mtry=21 : y = 5.39e+07 : 957.6 secs : infill_ei

Saved the current state after iteration 50 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 999 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 979 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 892 points instead of 1000!”

Growing trees.. Progress: 4%. Estimated remaining time: 13 minutes, 4 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 11 minutes, 56 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 11 minutes, 19 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 10 minutes, 29 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 10 minutes, 5 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 9 minutes, 32 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 8 minutes, 57 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 8 minutes, 27 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 7 minutes, 53 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 7 minutes, 23 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 6 minutes, 49 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 6 minutes, 16 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 5 minutes, 43 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 5 minutes, 11 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 4 minutes, 37 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 4 minutes, 5 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 3 minutes, 34 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 3 minutes, 0 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 2 minutes, 27 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 53 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 1 minute, 21 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 49 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 19 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 12 minutes, 9 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 11 minutes, 20 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 11 minutes, 5 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 10 minutes, 24 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 9 minutes, 47 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 9 minutes, 15 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 8 minutes, 40 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 8 minutes, 8 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 7 minutes, 36 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 7 minutes, 2 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 6 minutes, 32 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 6 minutes, 0 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 5 minutes, 27 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 4 minutes, 56 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 4 minutes, 25 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 3 minutes, 56 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 3 minutes, 23 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 2 minutes, 52 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 2 minutes, 19 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 46 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 1 minute, 14 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 43 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 13 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 11 minutes, 47 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 11 minutes, 26 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 10 minutes, 54 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 10 minutes, 11 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 9 minutes, 44 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 9 minutes, 6 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 8 minutes, 32 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 8 minutes, 1 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 7 minutes, 27 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 6 minutes, 53 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 6 minutes, 22 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 5 minutes, 48 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 5 minutes, 16 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 4 minutes, 45 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 4 minutes, 15 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 3 minutes, 44 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 3 minutes, 11 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 2 minutes, 39 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 2 minutes, 6 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 1 minute, 34 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 1 minute, 3 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 32 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 12 minutes, 9 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 11 minutes, 30 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 10 minutes, 49 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 10 minutes, 21 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 9 minutes, 54 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 9 minutes, 23 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 8 minutes, 50 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 8 minutes, 18 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 7 minutes, 44 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 7 minutes, 10 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 6 minutes, 41 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 6 minutes, 9 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 5 minutes, 37 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 5 minutes, 5 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 4 minutes, 34 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 4 minutes, 1 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 3 minutes, 27 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 2 minutes, 54 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 2 minutes, 22 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 50 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 1 minute, 17 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 45 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 12 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 12 minutes, 24 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 11 minutes, 45 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 11 minutes, 5 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 10 minutes, 24 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 9 minutes, 55 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 9 minutes, 20 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 8 minutes, 50 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 8 minutes, 16 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 7 minutes, 45 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 7 minutes, 14 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 6 minutes, 41 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 6 minutes, 9 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 5 minutes, 37 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 5 minutes, 3 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 4 minutes, 30 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 3 minutes, 58 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 3 minutes, 25 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 2 minutes, 52 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 2 minutes, 19 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 47 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 1 minute, 14 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 43 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 10 seconds.
20250921 234234	500	25	1000	40	5	54147000	66

[mbo] 50: num.trees=500; max.depth=25; min.node.size=1000; mtry=40 : y = 5.41e+07 : 3826.3 secs : infill_ei

Saved the current state after iteration 51 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 998 points instead of 1000!”

Growing trees.. Progress: 7%. Estimated remaining time: 6 minutes, 27 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 5 minutes, 51 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 5 minutes, 25 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 4 minutes, 51 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 4 minutes, 21 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 3 minutes, 50 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 3 minutes, 18 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 2 minutes, 45 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 2 minutes, 16 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 1 minute, 44 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 12 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 8 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 16 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 5 minutes, 40 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 5 minutes, 7 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 4 minutes, 38 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 4 minutes, 7 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 3 minutes, 34 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 3 minutes, 2 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 2 minutes, 32 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 2 minutes, 2 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 58 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 26 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 16 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 5 minutes, 45 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 5 minutes, 11 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 4 minutes, 38 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 4 minutes, 8 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 3 minutes, 36 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 3 minutes, 5 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 2 minutes, 34 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 2 minutes, 2 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 58 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 26 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 6 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 35 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 5 minutes, 10 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 4 minutes, 35 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 4 minutes, 1 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 3 minutes, 29 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 3 minutes, 0 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 2 minutes, 29 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 1 minute, 58 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 26 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 54 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 23 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 6 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 35 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 5 minutes, 10 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 4 minutes, 40 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 4 minutes, 9 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 3 minutes, 37 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 3 minutes, 4 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 2 minutes, 32 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 2 minutes, 1 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 59 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 26 seconds.
20250922 001743	500	26	1000	23	5	53913000	67

[mbo] 51: num.trees=500; max.depth=26; min.node.size=1000; mtry=23 : y = 5.39e+07 : 2103.0 secs : infill_ei

Saved the current state after iteration 52 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 883 points instead of 1000!”

Growing trees.. Progress: 14%. Estimated remaining time: 3 minutes, 7 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 2 minutes, 33 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 2 minutes, 2 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 1 minute, 32 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 1 minute, 0 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 29 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 3 minutes, 1 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 2 minutes, 30 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 1 minute, 58 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 1 minute, 26 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 55 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 24 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 3 minutes, 1 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 2 minutes, 28 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 1 minute, 58 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 1 minute, 27 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 57 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 27 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 2 minutes, 58 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 2 minutes, 28 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 1 minute, 57 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 1 minute, 26 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 55 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 23 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 2 minutes, 58 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 2 minutes, 27 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 1 minute, 58 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 1 minute, 27 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 56 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 25 seconds.
20250922 003642	500	24	492	12	5	54675000	68

[mbo] 52: num.trees=500; max.depth=24; min.node.size=492; mtry=12 : y = 5.47e+07 : 1135.3 secs : infill_ei

Saved the current state after iteration 53 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 513 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 456 points instead of 1000!”

Growing trees.. Progress: 4%. Estimated remaining time: 13 minutes, 30 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 12 minutes, 36 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 12 minutes, 5 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 11 minutes, 27 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 10 minutes, 48 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 10 minutes, 24 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 9 minutes, 53 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 9 minutes, 24 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 8 minutes, 53 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 8 minutes, 23 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 7 minutes, 51 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 7 minutes, 16 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 6 minutes, 42 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 6 minutes, 11 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 5 minutes, 39 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 5 minutes, 6 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 4 minutes, 33 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 4 minutes, 0 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 3 minutes, 27 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 2 minutes, 56 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 2 minutes, 23 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 51 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 1 minute, 18 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 45 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 13 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 13 minutes, 4 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 12 minutes, 24 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 11 minutes, 56 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 11 minutes, 27 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 10 minutes, 56 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 10 minutes, 24 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 9 minutes, 50 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 9 minutes, 20 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 8 minutes, 48 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 8 minutes, 16 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 7 minutes, 42 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 7 minutes, 9 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 6 minutes, 37 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 6 minutes, 4 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 5 minutes, 31 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 4 minutes, 59 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 4 minutes, 26 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 3 minutes, 53 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 3 minutes, 21 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 2 minutes, 48 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 2 minutes, 15 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 1 minute, 42 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 1 minute, 10 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 6 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 13 minutes, 4 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 12 minutes, 12 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 11 minutes, 42 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 11 minutes, 16 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 10 minutes, 44 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 10 minutes, 11 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 9 minutes, 41 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 9 minutes, 9 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 8 minutes, 36 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 8 minutes, 2 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 7 minutes, 31 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 6 minutes, 58 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 6 minutes, 26 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 5 minutes, 57 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 5 minutes, 25 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 4 minutes, 53 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 4 minutes, 21 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 3 minutes, 48 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 3 minutes, 16 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 2 minutes, 44 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 2 minutes, 10 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 38 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 1 minute, 5 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 33 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 13 minutes, 30 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 12 minutes, 16 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 11 minutes, 51 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 11 minutes, 17 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 10 minutes, 44 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 10 minutes, 11 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 9 minutes, 38 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 9 minutes, 8 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 8 minutes, 35 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 8 minutes, 3 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 7 minutes, 33 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 7 minutes, 0 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 6 minutes, 27 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 5 minutes, 55 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 5 minutes, 22 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 4 minutes, 50 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 4 minutes, 17 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 3 minutes, 45 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 3 minutes, 12 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 2 minutes, 40 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 2 minutes, 8 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 34 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 13 minutes, 55 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 12 minutes, 48 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 12 minutes, 11 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 11 minutes, 43 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 11 minutes, 9 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 10 minutes, 39 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 10 minutes, 2 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 9 minutes, 29 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 8 minutes, 57 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 8 minutes, 27 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 7 minutes, 54 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 7 minutes, 21 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 6 minutes, 49 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 6 minutes, 15 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 5 minutes, 41 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 5 minutes, 9 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 4 minutes, 36 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 4 minutes, 5 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 3 minutes, 32 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 2 minutes, 59 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 2 minutes, 26 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 53 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 1 minute, 20 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 47 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 14 seconds.
20250922 014549	500	20	982	45	5	54324000	69

[mbo] 53: num.trees=500; max.depth=20; min.node.size=982; mtry=45 : y = 5.43e+07 : 4140.6 secs : infill_ei

Saved the current state after iteration 54 in the file HT450.RDATA.

Growing trees.. Progress: 28%. Estimated remaining time: 1 minute, 21 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 50 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 18 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 1 minute, 18 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 47 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 16 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 1 minute, 18 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 46 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 15 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 1 minute, 21 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 49 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 17 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 1 minute, 21 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 49 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 17 seconds.
20250922 015538	156	20	503	20	5	54213000	70

[mbo] 54: num.trees=156; max.depth=20; min.node.size=503; mtry=20 : y = 5.42e+07 : 585.1 secs : infill_ei

Growing trees.. Progress: 34%. Estimated remaining time: 59 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 27 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 56 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 25 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 57 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 26 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 1 minute, 1 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 28 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 1 minute, 3 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 30 seconds.
20250922 020337	146	28	458	17	5	55218000	71

[mbo] 55: num.trees=146; max.depth=28; min.node.size=458; mtry=17 : y = 5.52e+07 : 478.3 secs : infill_ei

Saved the current state after iteration 56 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 873 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 999 points instead of 1000!”

Growing trees.. Progress: 5%. Estimated remaining time: 9 minutes, 25 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 8 minutes, 51 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 8 minutes, 11 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 7 minutes, 35 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 7 minutes, 2 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 6 minutes, 31 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 5 minutes, 56 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 5 minutes, 25 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 4 minutes, 54 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 4 minutes, 22 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 3 minutes, 50 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 3 minutes, 18 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 2 minutes, 45 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 2 minutes, 14 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 43 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 1 minute, 13 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 8 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 9 minutes, 3 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 8 minutes, 29 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 7 minutes, 59 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 7 minutes, 26 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 6 minutes, 51 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 6 minutes, 21 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 5 minutes, 49 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 5 minutes, 16 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 4 minutes, 45 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 4 minutes, 13 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 3 minutes, 43 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 3 minutes, 11 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 2 minutes, 39 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 2 minutes, 9 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 37 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 1 minute, 5 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 33 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 2 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 9 minutes, 3 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 8 minutes, 32 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 8 minutes, 4 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 7 minutes, 35 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 7 minutes, 5 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 6 minutes, 31 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 6 minutes, 0 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 5 minutes, 27 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 4 minutes, 53 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 4 minutes, 21 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 3 minutes, 50 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 3 minutes, 17 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 2 minutes, 46 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 2 minutes, 15 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 43 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 12 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 9 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 9 minutes, 25 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 8 minutes, 51 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 8 minutes, 18 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 7 minutes, 42 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 7 minutes, 8 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 6 minutes, 35 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 6 minutes, 5 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 5 minutes, 32 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 5 minutes, 0 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 4 minutes, 28 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 3 minutes, 55 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 3 minutes, 22 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 2 minutes, 50 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 2 minutes, 18 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 47 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 1 minute, 14 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 41 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 9 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 9 minutes, 25 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 9 minutes, 2 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 8 minutes, 28 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 8 minutes, 3 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 7 minutes, 29 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 6 minutes, 58 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 6 minutes, 26 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 5 minutes, 52 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 5 minutes, 18 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 4 minutes, 46 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 4 minutes, 12 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 3 minutes, 40 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 3 minutes, 7 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 2 minutes, 36 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 2 minutes, 5 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 32 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 1 minute, 1 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
20250922 025340	500	30	1000	32	5	54240000	72

[mbo] 56: num.trees=500; max.depth=30; min.node.size=1000; mtry=32 : y = 5.42e+07 : 2998.1 secs : infill_ei

Saved the current state after iteration 57 in the file HT450.RDATA.

Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 0 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 3 minutes, 22 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 2 minutes, 54 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 2 minutes, 20 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 1 minute, 48 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 1 minute, 15 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 44 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 13 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 47 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 3 minutes, 16 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 2 minutes, 45 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 2 minutes, 14 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 1 minute, 43 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 1 minute, 11 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 8 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 47 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 3 minutes, 12 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 2 minutes, 41 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 2 minutes, 10 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 1 minute, 38 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 1 minute, 7 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 35 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 3 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 47 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 3 minutes, 16 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 2 minutes, 43 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 2 minutes, 13 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 1 minute, 41 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 1 minute, 10 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 7 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 51 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 3 minutes, 18 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 2 minutes, 47 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 2 minutes, 15 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 1 minute, 42 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 1 minute, 11 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 8 seconds.
20250922 031630	500	30	843	15	5	55191000	73

[mbo] 57: num.trees=500; max.depth=30; min.node.size=843; mtry=15 : y = 5.52e+07 : 1364.1 secs : infill_ei

Saved the current state after iteration 58 in the file HT450.RDATA.

Growing trees.. Progress: 24%. Estimated remaining time: 1 minute, 36 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 1 minute, 4 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 32 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 1 minute, 34 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 1 minute, 36 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 1 minute, 4 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 32 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 1 minute, 36 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 1 minute, 5 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 34 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 3 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 1 minute, 38 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 1 minute, 7 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 34 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 2 seconds.
20250922 032743	230	30	903	16	5	54891000	74

[mbo] 58: num.trees=230; max.depth=30; min.node.size=903; mtry=16 : y = 5.49e+07 : 669.6 secs : infill_ei

Saved the current state after iteration 59 in the file HT450.RDATA.

Growing trees.. Progress: 27%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 54 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 22 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 1 minute, 26 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 55 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 24 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 54 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 23 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 1 minute, 26 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 53 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 22 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 1 minute, 29 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 57 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 26 seconds.
20250922 033821	338	16	833	11	5	55263000	75

[mbo] 59: num.trees=338; max.depth=16; min.node.size=833; mtry=11 : y = 5.53e+07 : 632.8 secs : infill_ei

Saved the current state after iteration 60 in the file HT450.RDATA.

Growing trees.. Progress: 6%. Estimated remaining time: 9 minutes, 6 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 8 minutes, 15 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 7 minutes, 43 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 7 minutes, 12 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 6 minutes, 43 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 6 minutes, 10 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 5 minutes, 42 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 5 minutes, 14 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 4 minutes, 45 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 4 minutes, 15 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 3 minutes, 45 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 3 minutes, 15 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 2 minutes, 44 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 2 minutes, 15 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 44 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 1 minute, 14 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 43 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 11 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 9 minutes, 59 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 9 minutes, 37 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 9 minutes, 8 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 8 minutes, 38 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 8 minutes, 10 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 7 minutes, 43 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 7 minutes, 47 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 8 minutes, 17 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 8 minutes, 37 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 8 minutes, 36 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 8 minutes, 5 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 7 minutes, 19 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 6 minutes, 36 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 5 minutes, 54 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 5 minutes, 9 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 4 minutes, 24 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 3 minutes, 43 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 3 minutes, 0 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 2 minutes, 20 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 1 minute, 35 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 55 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 17 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 9 minutes, 34 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 9 minutes, 8 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 8 minutes, 32 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 7 minutes, 58 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 7 minutes, 25 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 6 minutes, 50 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 6 minutes, 16 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 5 minutes, 43 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 5 minutes, 11 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 4 minutes, 39 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 4 minutes, 7 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 3 minutes, 33 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 3 minutes, 1 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 2 minutes, 28 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 1 minute, 55 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 22 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 51 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 17 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 9 minutes, 10 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 8 minutes, 37 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 8 minutes, 4 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 7 minutes, 28 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 6 minutes, 54 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 6 minutes, 22 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 5 minutes, 48 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 5 minutes, 15 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 4 minutes, 42 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 4 minutes, 10 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 3 minutes, 37 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 3 minutes, 4 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 2 minutes, 31 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 1 minute, 59 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 29 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 1 minute, 3 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 32 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 2 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 10 minutes, 26 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 9 minutes, 33 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 8 minutes, 54 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 8 minutes, 16 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 7 minutes, 46 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 7 minutes, 23 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 6 minutes, 59 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 6 minutes, 26 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 5 minutes, 55 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 5 minutes, 21 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 4 minutes, 48 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 4 minutes, 12 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 3 minutes, 40 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 3 minutes, 5 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 2 minutes, 31 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 2 minutes, 0 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 27 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 53 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 23 seconds.
20250922 043111	488	14	496	39	5	55209000	76

[mbo] 60: num.trees=488; max.depth=14; min.node.size=496; mtry=39 : y = 5.52e+07 : 3164.9 secs : infill_ei

Saved the current state after iteration 61 in the file HT450.RDATA.

Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 7 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 5 minutes, 53 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 5 minutes, 20 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 4 minutes, 42 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 4 minutes, 11 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 3 minutes, 40 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 3 minutes, 7 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 2 minutes, 35 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 2 minutes, 6 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 34 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 4 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 36 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 13 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 9 minutes, 19 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 8 minutes, 48 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 8 minutes, 47 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 7 minutes, 27 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 6 minutes, 20 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 5 minutes, 23 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 4 minutes, 38 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 3 minutes, 56 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 3 minutes, 19 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 2 minutes, 42 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 2 minutes, 5 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 1 minute, 31 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 56 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 22 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 6 minutes, 30 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 5 minutes, 59 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 5 minutes, 24 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 4 minutes, 50 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 4 minutes, 17 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 3 minutes, 42 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 3 minutes, 9 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 2 minutes, 37 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 2 minutes, 5 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 34 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 3 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 32 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 18 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 5 minutes, 42 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 5 minutes, 9 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 4 minutes, 33 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 4 minutes, 2 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 3 minutes, 31 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 3 minutes, 2 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 2 minutes, 30 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 1 minute, 59 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 32 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 3 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 7 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 31 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 5 minutes, 1 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 4 minutes, 28 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 3 minutes, 53 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 3 minutes, 20 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 2 minutes, 47 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 2 minutes, 14 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 1 minute, 42 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 11 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 38 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 6 seconds.
20250922 050723	476	14	813	27	5	54852000	77

[mbo] 61: num.trees=476; max.depth=14; min.node.size=813; mtry=27 : y = 5.49e+07 : 2164.7 secs : infill_ei

Saved the current state after iteration 62 in the file HT450.RDATA.

Growing trees.. Progress: 5%. Estimated remaining time: 10 minutes, 42 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 9 minutes, 39 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 9 minutes, 6 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 8 minutes, 38 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 8 minutes, 2 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 7 minutes, 32 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 7 minutes, 1 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 6 minutes, 28 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 5 minutes, 56 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 5 minutes, 23 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 4 minutes, 53 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 4 minutes, 23 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 3 minutes, 52 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 3 minutes, 21 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 2 minutes, 52 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 2 minutes, 22 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 51 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 20 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 48 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 17 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 11 minutes, 3 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 10 minutes, 21 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 9 minutes, 49 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 9 minutes, 12 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 8 minutes, 50 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 8 minutes, 16 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 7 minutes, 45 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 7 minutes, 10 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 6 minutes, 35 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 6 minutes, 3 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 5 minutes, 29 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 4 minutes, 56 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 4 minutes, 24 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 3 minutes, 52 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 3 minutes, 21 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 2 minutes, 48 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 2 minutes, 15 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 42 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 38 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 6 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 11 minutes, 3 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 10 minutes, 26 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 9 minutes, 58 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 9 minutes, 25 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 8 minutes, 56 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 8 minutes, 44 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 8 minutes, 29 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 8 minutes, 11 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 7 minutes, 50 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 7 minutes, 34 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 7 minutes, 6 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 6 minutes, 35 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 6 minutes, 1 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 5 minutes, 25 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 4 minutes, 50 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 4 minutes, 14 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 3 minutes, 40 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 3 minutes, 5 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 2 minutes, 30 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 54 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 1 minute, 21 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 48 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 15 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 11 minutes, 47 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 10 minutes, 58 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 10 minutes, 29 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 9 minutes, 53 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 9 minutes, 16 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 8 minutes, 44 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 8 minutes, 7 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 7 minutes, 31 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 6 minutes, 58 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 6 minutes, 26 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 5 minutes, 51 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 5 minutes, 17 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 4 minutes, 42 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 4 minutes, 9 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 3 minutes, 35 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 3 minutes, 3 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 2 minutes, 31 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 59 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 1 minute, 29 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 1 minute, 1 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 33 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 5 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 12 minutes, 32 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 12 minutes, 7 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 11 minutes, 30 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 11 minutes, 2 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 10 minutes, 20 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 9 minutes, 45 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 9 minutes, 5 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 8 minutes, 22 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 7 minutes, 39 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 7 minutes, 5 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 6 minutes, 32 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 5 minutes, 57 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 5 minutes, 19 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 4 minutes, 41 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 4 minutes, 4 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 3 minutes, 27 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 2 minutes, 51 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 2 minutes, 14 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 39 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 1 minute, 3 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 29 seconds.
20250922 060706	500	16	998	40	5	54825000	78

[mbo] 62: num.trees=500; max.depth=16; min.node.size=998; mtry=40 : y = 5.48e+07 : 3577.4 secs : infill_ei

Saved the current state after iteration 63 in the file HT450.RDATA.

Growing trees.. Progress: 7%. Estimated remaining time: 7 minutes, 18 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 6 minutes, 47 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 6 minutes, 25 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 5 minutes, 58 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 5 minutes, 29 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 5 minutes, 1 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 4 minutes, 29 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 3 minutes, 57 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 3 minutes, 26 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 2 minutes, 55 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 2 minutes, 22 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 51 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 19 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 47 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 15 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 7 minutes, 49 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 7 minutes, 10 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 6 minutes, 41 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 6 minutes, 7 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 5 minutes, 34 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 5 minutes, 5 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 4 minutes, 34 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 4 minutes, 3 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 3 minutes, 33 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 3 minutes, 1 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 2 minutes, 30 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 1 minute, 58 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 27 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 55 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 23 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 7 minutes, 49 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 7 minutes, 17 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 6 minutes, 45 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 6 minutes, 13 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 5 minutes, 42 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 5 minutes, 11 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 4 minutes, 39 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 4 minutes, 8 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 3 minutes, 39 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 3 minutes, 7 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 2 minutes, 34 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 2 minutes, 2 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 57 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 25 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 7 minutes, 49 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 7 minutes, 10 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 6 minutes, 36 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 6 minutes, 7 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 5 minutes, 36 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 5 minutes, 4 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 4 minutes, 33 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 3 minutes, 59 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 3 minutes, 28 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 2 minutes, 55 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 2 minutes, 24 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 51 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 19 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 47 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 16 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 7 minutes, 18 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 6 minutes, 47 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 6 minutes, 11 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 5 minutes, 37 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 5 minutes, 8 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 4 minutes, 37 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 4 minutes, 6 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 3 minutes, 35 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 3 minutes, 3 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 2 minutes, 33 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 2 minutes, 3 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 1 minute, 31 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 1 minute, 1 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 31 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
20250922 064905	500	12	486	37	5	55137000	79

[mbo] 63: num.trees=500; max.depth=12; min.node.size=486; mtry=37 : y = 5.51e+07 : 2512.9 secs : infill_ei

Saved the current state after iteration 64 in the file HT450.RDATA.

Growing trees.. Progress: 26%. Estimated remaining time: 1 minute, 28 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 53 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 22 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 1 minute, 18 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 49 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 17 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 1 minute, 16 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 45 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 15 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 1 minute, 23 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 51 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 20 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 1 minute, 23 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 22 seconds.
20250922 065910	166	27	371	18	5	53682000	80

[mbo] 64: num.trees=166; max.depth=27; min.node.size=371; mtry=18 : y = 5.37e+07 : 598.0 secs : infill_ei

Growing trees.. Progress: 34%. Estimated remaining time: 1 minute, 0 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 1 minute, 4 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 33 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 2 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 1 minute, 4 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 33 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 1 minute, 0 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 30 seconds.
20250922 070730	130	29	938	19	5	54411000	81

[mbo] 65: num.trees=130; max.depth=29; min.node.size=938; mtry=19 : y = 5.44e+07 : 500.8 secs : infill_ei

Saved the current state after iteration 66 in the file HT450.RDATA.

Growing trees.. Progress: 15%. Estimated remaining time: 2 minutes, 50 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 2 minutes, 19 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 1 minute, 48 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 1 minute, 17 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 46 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 13 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 40 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 2 minutes, 9 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 1 minute, 38 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 37 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 5 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 40 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 2 minutes, 7 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 1 minute, 36 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 1 minute, 6 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 34 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 4 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 40 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 2 minutes, 9 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 1 minute, 38 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 1 minute, 7 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 36 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 5 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 2 minutes, 50 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 2 minutes, 16 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 1 minute, 46 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 1 minute, 14 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 42 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 11 seconds.
20250922 072439	266	16	999	22	5	53934000	82

[mbo] 66: num.trees=266; max.depth=16; min.node.size=999; mtry=22 : y = 5.39e+07 : 1023.0 secs : infill_ei

Saved the current state after iteration 67 in the file HT450.RDATA.

Growing trees.. Progress: 7%. Estimated remaining time: 6 minutes, 24 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 5 minutes, 53 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 5 minutes, 13 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 4 minutes, 41 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 4 minutes, 9 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 3 minutes, 37 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 3 minutes, 4 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 2 minutes, 31 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 2 minutes, 0 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 29 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 59 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 27 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 13 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 36 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 5 minutes, 9 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 4 minutes, 34 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 4 minutes, 2 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 3 minutes, 28 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 2 minutes, 56 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 2 minutes, 24 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 1 minute, 53 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 1 minute, 21 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 49 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 17 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 12 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 41 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 5 minutes, 9 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 4 minutes, 35 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 4 minutes, 1 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 3 minutes, 28 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 2 minutes, 58 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 2 minutes, 27 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 1 minute, 56 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 1 minute, 24 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 20 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 12 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 36 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 5 minutes, 3 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 4 minutes, 30 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 4 minutes, 1 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 3 minutes, 28 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 2 minutes, 56 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 2 minutes, 25 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 1 minute, 55 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 1 minute, 24 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 51 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 18 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 13 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 36 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 5 minutes, 6 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 4 minutes, 40 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 4 minutes, 10 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 3 minutes, 41 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 3 minutes, 12 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 2 minutes, 43 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 2 minutes, 15 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 1 minute, 45 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 1 minute, 19 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 50 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 20 seconds.
20250922 075956	469	28	880	23	5	54450000	83

[mbo] 67: num.trees=469; max.depth=28; min.node.size=880; mtry=23 : y = 5.44e+07 : 2111.6 secs : infill_ei

Saved the current state after iteration 68 in the file HT450.RDATA.

Growing trees.. Progress: 21%. Estimated remaining time: 1 minute, 53 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 1 minute, 18 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 47 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 16 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 1 minute, 50 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 1 minute, 18 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 47 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 15 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 2 minutes, 3 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 1 minute, 34 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 59 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 24 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 1 minute, 43 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 1 minute, 10 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 7 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 1 minute, 42 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 37 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 6 seconds.
20250922 081220	378	10	530	15	5	54030000	84

[mbo] 68: num.trees=378; max.depth=10; min.node.size=530; mtry=15 : y = 5.4e+07 : 736.3 secs : infill_ei

Saved the current state after iteration 69 in the file HT450.RDATA.

20250922 081539	375	12	145	2	5	52167000	85

[mbo] 69: num.trees=375; max.depth=12; min.node.size=145; mtry=2 : y = 5.22e+07 : 194.7 secs : infill_ei

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 600 points instead of 1000!”

20250922 081651	20	29	564	15	5	50586000	86

[mbo] 70: num.trees=20; max.depth=29; min.node.size=564; mtry=15 : y = 5.06e+07 : 71.4 secs : infill_ei

Growing trees.. Progress: 14%. Estimated remaining time: 3 minutes, 4 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 2 minutes, 31 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 2 minutes, 2 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 1 minute, 29 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 56 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 25 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 2 minutes, 52 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 2 minutes, 21 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 1 minute, 51 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 1 minute, 19 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 50 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 20 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 2 minutes, 55 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 2 minutes, 24 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 1 minute, 53 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 1 minute, 24 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 53 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 22 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 2 minutes, 58 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 2 minutes, 24 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 1 minute, 54 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 1 minute, 24 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 54 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 23 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 3 minutes, 10 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 2 minutes, 39 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 2 minutes, 9 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 1 minute, 39 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 1 minute, 7 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 34 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 2 seconds.
20250922 083542	500	22	858	12	5	54708000	87

[mbo] 71: num.trees=500; max.depth=22; min.node.size=858; mtry=12 : y = 5.47e+07 : 1131.1 secs : infill_ei

Saved the current state after iteration 72 in the file HT450.RDATA.

20250922 083759	41	25	301	14	5	50787000	88

[mbo] 72: num.trees=41; max.depth=25; min.node.size=301; mtry=14 : y = 5.08e+07 : 129.8 secs : infill_ei

Growing trees.. Progress: 13%. Estimated remaining time: 3 minutes, 36 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 3 minutes, 5 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 2 minutes, 34 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 2 minutes, 4 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 1 minute, 32 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 29 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 41 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 3 minutes, 13 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 2 minutes, 41 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 2 minutes, 7 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 1 minute, 36 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 1 minute, 5 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 34 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 3 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 3 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 3 minutes, 27 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 3 minutes, 3 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 2 minutes, 30 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 2 minutes, 1 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 1 minute, 34 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 1 minute, 8 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 9 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 16 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 3 minutes, 45 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 3 minutes, 5 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 2 minutes, 32 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 1 minute, 59 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 1 minute, 27 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 53 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 19 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 46 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 3 minutes, 16 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 2 minutes, 41 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 2 minutes, 8 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 1 minute, 36 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 1 minute, 4 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 32 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 1 seconds.
20250922 090040	399	9	213	33	5	54840000	89

[mbo] 73: num.trees=399; max.depth=9; min.node.size=213; mtry=33 : y = 5.48e+07 : 1360.5 secs : infill_ei

Saved the current state after iteration 74 in the file HT450.RDATA.

Growing trees.. Progress: 6%. Estimated remaining time: 8 minutes, 48 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 8 minutes, 13 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 7 minutes, 39 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 7 minutes, 4 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 6 minutes, 34 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 6 minutes, 1 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 5 minutes, 27 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 4 minutes, 55 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 4 minutes, 21 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 3 minutes, 48 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 3 minutes, 16 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 2 minutes, 44 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 2 minutes, 15 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 1 minute, 45 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 1 minute, 12 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 7 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 8 minutes, 54 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 8 minutes, 23 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 7 minutes, 52 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 7 minutes, 21 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 6 minutes, 44 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 6 minutes, 10 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 5 minutes, 36 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 5 minutes, 5 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 4 minutes, 33 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 4 minutes, 1 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 3 minutes, 30 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 2 minutes, 58 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 2 minutes, 26 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 1 minute, 53 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 21 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 48 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 15 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 8 minutes, 27 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 7 minutes, 47 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 7 minutes, 18 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 6 minutes, 40 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 6 minutes, 4 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 5 minutes, 33 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 5 minutes, 3 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 4 minutes, 29 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 3 minutes, 58 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 3 minutes, 23 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 2 minutes, 53 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 2 minutes, 22 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 1 minute, 51 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 18 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 45 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 14 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 7 minutes, 51 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 7 minutes, 28 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 6 minutes, 58 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 6 minutes, 20 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 5 minutes, 50 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 5 minutes, 17 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 4 minutes, 44 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 4 minutes, 10 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 3 minutes, 38 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 3 minutes, 7 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 2 minutes, 35 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 2 minutes, 5 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 1 minute, 36 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 1 minute, 6 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 38 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 13 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 10 minutes, 47 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 12 minutes, 53 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 13 minutes, 10 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 12 minutes, 50 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 12 minutes, 20 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 12 minutes, 4 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 11 minutes, 32 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 11 minutes, 15 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 11 minutes, 7 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 10 minutes, 4 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 8 minutes, 49 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 7 minutes, 37 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 6 minutes, 27 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 5 minutes, 24 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 4 minutes, 30 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 3 minutes, 39 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 2 minutes, 52 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 2 minutes, 7 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 23 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 1 seconds.
20250922 094841	438	13	432	41	5	54999000	90

[mbo] 74: num.trees=438; max.depth=13; min.node.size=432; mtry=41 : y = 5.5e+07 : 2876.8 secs : infill_ei

Saved the current state after iteration 75 in the file HT450.RDATA.

Growing trees.. Progress: 24%. Estimated remaining time: 1 minute, 39 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 1 minute, 4 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 34 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 3 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 1 minute, 36 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 1 minute, 4 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 33 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 2 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 1 minute, 39 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 1 minute, 6 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 35 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 3 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 1 minute, 39 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 1 minute, 5 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 33 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 1 minute, 36 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 31 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 0 seconds.
20250922 100005	136	28	510	24	5	54267000	91

[mbo] 75: num.trees=136; max.depth=28; min.node.size=510; mtry=24 : y = 5.43e+07 : 678.1 secs : infill_ei

Saved the current state after iteration 76 in the file HT450.RDATA.

Growing trees.. Progress: 11%. Estimated remaining time: 3 minutes, 59 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 3 minutes, 26 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 2 minutes, 56 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 2 minutes, 23 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 1 minute, 51 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 1 minute, 19 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 48 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 18 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 50 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 3 minutes, 20 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 2 minutes, 47 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 2 minutes, 16 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 1 minute, 46 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 1 minute, 12 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 41 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 9 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 46 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 3 minutes, 12 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 2 minutes, 40 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 2 minutes, 8 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 1 minute, 36 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 1 minute, 4 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 33 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 2 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 38 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 3 minutes, 7 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 2 minutes, 40 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 2 minutes, 9 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 1 minute, 38 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 1 minute, 7 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 35 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 4 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 50 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 3 minutes, 13 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 2 minutes, 42 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 2 minutes, 14 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 1 minute, 42 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 1 minute, 10 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 8 seconds.
20250922 102304	498	24	859	14	5	55230000	92

[mbo] 76: num.trees=498; max.depth=24; min.node.size=859; mtry=14 : y = 5.52e+07 : 1375.4 secs : infill_ei

Saved the current state after iteration 77 in the file HT450.RDATA.

Growing trees.. Progress: 19%. Estimated remaining time: 2 minutes, 11 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 1 minute, 40 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 1 minute, 10 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 8 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 2 minutes, 19 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 1 minute, 49 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 1 minute, 17 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 45 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 14 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 2 minutes, 19 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 1 minute, 46 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 1 minute, 15 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 43 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 12 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 2 minutes, 19 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 1 minute, 44 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 1 minute, 13 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 42 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 10 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 2 minutes, 19 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 1 minute, 40 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 1 minute, 10 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 8 seconds.
20250922 103751	247	26	454	17	5	55050000	93

[mbo] 77: num.trees=247; max.depth=26; min.node.size=454; mtry=17 : y = 5.5e+07 : 881.2 secs : infill_ei

Saved the current state after iteration 78 in the file HT450.RDATA.

Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 20 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 3 minutes, 49 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 3 minutes, 16 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 2 minutes, 42 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 2 minutes, 10 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 1 minute, 39 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 6 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 34 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 3 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 8 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 3 minutes, 37 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 3 minutes, 4 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 2 minutes, 34 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 2 minutes, 2 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 59 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 28 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 14 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 3 minutes, 37 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 3 minutes, 10 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 2 minutes, 38 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 2 minutes, 8 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 1 minute, 35 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 3 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 31 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 14 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 3 minutes, 37 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 3 minutes, 4 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 2 minutes, 32 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 2 minutes, 1 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 59 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 28 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 16 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 3 minutes, 41 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 3 minutes, 8 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 2 minutes, 36 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 2 minutes, 7 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 1 minute, 37 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 5 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 34 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 1 seconds.
20250922 110236	460	15	436	18	5	55071000	94

[mbo] 78: num.trees=460; max.depth=15; min.node.size=436; mtry=18 : y = 5.51e+07 : 1479.0 secs : infill_ei

Saved the current state after iteration 79 in the file HT450.RDATA.

Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 51 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 4 minutes, 28 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 3 minutes, 57 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 3 minutes, 27 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 2 minutes, 58 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 2 minutes, 26 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 1 minute, 55 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 1 minute, 23 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 50 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 17 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 5 minutes, 0 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 4 minutes, 29 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 3 minutes, 52 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 3 minutes, 20 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 2 minutes, 47 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 2 minutes, 15 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 1 minute, 43 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 11 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 9 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 5 minutes, 10 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 4 minutes, 34 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 4 minutes, 4 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 3 minutes, 36 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 3 minutes, 3 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 2 minutes, 30 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 1 minute, 56 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 1 minute, 22 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 49 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 18 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 5 minutes, 10 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 4 minutes, 33 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 3 minutes, 58 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 3 minutes, 28 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 2 minutes, 53 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 2 minutes, 20 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 1 minute, 48 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 1 minute, 17 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 46 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 14 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 51 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 4 minutes, 20 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 3 minutes, 49 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 3 minutes, 14 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 2 minutes, 42 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 2 minutes, 10 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 1 minute, 37 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 1 minute, 6 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 35 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 5 seconds.
20250922 113103	385	14	357	26	5	55197000	95

[mbo] 79: num.trees=385; max.depth=14; min.node.size=357; mtry=26 : y = 5.52e+07 : 1701.1 secs : infill_ei

Saved the current state after iteration 80 in the file HT450.RDATA.

Growing trees.. Progress: 6%. Estimated remaining time: 8 minutes, 10 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 7 minutes, 18 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 6 minutes, 40 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 6 minutes, 5 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 5 minutes, 33 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 5 minutes, 2 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 4 minutes, 29 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 3 minutes, 56 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 3 minutes, 23 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 2 minutes, 52 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 2 minutes, 21 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 49 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 16 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 44 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 11 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 7 minutes, 34 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 7 minutes, 10 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 6 minutes, 35 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 6 minutes, 10 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 5 minutes, 42 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 5 minutes, 17 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 4 minutes, 57 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 4 minutes, 43 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 4 minutes, 37 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 4 minutes, 30 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 4 minutes, 25 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 4 minutes, 17 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 4 minutes, 5 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 3 minutes, 53 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 3 minutes, 39 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 3 minutes, 20 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 2 minutes, 57 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 2 minutes, 27 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 57 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 46 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 3 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 8 minutes, 10 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 7 minutes, 27 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 6 minutes, 54 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 6 minutes, 21 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 5 minutes, 48 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 5 minutes, 15 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 4 minutes, 41 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 4 minutes, 8 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 3 minutes, 34 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 3 minutes, 2 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 2 minutes, 29 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 1 minute, 56 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 26 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 53 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 20 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 7 minutes, 48 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 7 minutes, 1 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 6 minutes, 30 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 5 minutes, 58 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 5 minutes, 29 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 4 minutes, 55 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 4 minutes, 27 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 3 minutes, 59 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 3 minutes, 34 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 3 minutes, 9 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 2 minutes, 44 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 2 minutes, 14 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 1 minute, 44 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 15 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 44 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 11 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 8 minutes, 51 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 7 minutes, 59 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 7 minutes, 21 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 6 minutes, 50 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 6 minutes, 38 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 6 minutes, 15 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 5 minutes, 44 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 5 minutes, 15 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 4 minutes, 42 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 4 minutes, 10 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 3 minutes, 37 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 3 minutes, 5 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 2 minutes, 33 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 2 minutes, 1 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 28 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 54 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 21 seconds.
20250922 121813	454	10	763	50	5	55215000	96

[mbo] 80: num.trees=454; max.depth=10; min.node.size=763; mtry=50 : y = 5.52e+07 : 2824.8 secs : infill_ei

Saved the current state after iteration 81 in the file HT450.RDATA.

Growing trees.. Progress: 36%. Estimated remaining time: 54 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 23 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 1 minute, 0 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 27 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 56 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 23 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 53 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 21 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 56 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 23 seconds.
20250922 122644	500	16	838	4	5	53679000	97

[mbo] 81: num.trees=500; max.depth=16; min.node.size=838; mtry=4 : y = 5.37e+07 : 506.7 secs : infill_ei

Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 16 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 42 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 5 minutes, 12 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 4 minutes, 42 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 4 minutes, 10 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 3 minutes, 37 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 3 minutes, 7 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 2 minutes, 36 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 2 minutes, 6 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 33 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 3 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 32 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 2 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 6 minutes, 49 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 6 minutes, 3 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 5 minutes, 30 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 4 minutes, 56 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 4 minutes, 27 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 3 minutes, 58 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 3 minutes, 22 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 2 minutes, 48 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 2 minutes, 16 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 1 minute, 42 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 34 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 5 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 26 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 4 minutes, 56 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 4 minutes, 25 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 3 minutes, 54 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 3 minutes, 21 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 2 minutes, 46 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 2 minutes, 13 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 1 minute, 41 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 10 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 8 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 6 minutes, 36 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 5 minutes, 57 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 5 minutes, 25 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 4 minutes, 51 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 4 minutes, 21 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 3 minutes, 47 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 3 minutes, 13 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 2 minutes, 44 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 2 minutes, 13 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 1 minute, 42 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 10 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 7 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 6 minutes, 36 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 6 minutes, 5 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 5 minutes, 34 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 4 minutes, 56 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 4 minutes, 22 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 3 minutes, 48 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 3 minutes, 15 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 2 minutes, 41 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 2 minutes, 9 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 1 minute, 38 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 10 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 9 seconds.
20250922 130205	345	16	774	31	5	54216000	98

[mbo] 82: num.trees=345; max.depth=16; min.node.size=774; mtry=31 : y = 5.42e+07 : 2120.3 secs : infill_ei

Saved the current state after iteration 83 in the file HT450.RDATA.

Growing trees.. Progress: 20%. Estimated remaining time: 2 minutes, 0 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 1 minute, 35 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 2 minutes, 2 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 53 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 20 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 1 minute, 44 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 1 minute, 14 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 44 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 14 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 1 minute, 47 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 1 minute, 14 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 45 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 13 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 1 minute, 44 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 1 minute, 13 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 43 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 12 seconds.
20250922 131500	327	16	432	11	5	55431000	99
20250922 131501	327	16	432	11	5	55431000	99

[mbo] 83: num.trees=327; max.depth=16; min.node.size=432; mtry=11 : y = 5.54e+07 : 769.1 secs : infill_ei

Saved the current state after iteration 84 in the file HT450.RDATA.

Growing trees.. Progress: 8%. Estimated remaining time: 5 minutes, 35 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 5 minutes, 4 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 4 minutes, 36 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 4 minutes, 3 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 3 minutes, 27 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 2 minutes, 56 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 2 minutes, 23 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 1 minute, 51 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 18 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 48 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 16 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 5 minutes, 35 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 5 minutes, 10 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 4 minutes, 33 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 4 minutes, 2 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 3 minutes, 27 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 2 minutes, 52 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 2 minutes, 20 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 1 minute, 48 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 1 minute, 16 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 45 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 13 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 5 minutes, 35 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 4 minutes, 54 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 4 minutes, 23 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 3 minutes, 49 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 3 minutes, 18 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 2 minutes, 47 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 2 minutes, 15 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 1 minute, 45 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 1 minute, 14 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 45 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 16 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 5 minutes, 35 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 4 minutes, 59 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 4 minutes, 29 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 4 minutes, 1 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 3 minutes, 28 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 2 minutes, 56 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 2 minutes, 23 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 1 minute, 51 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 20 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 49 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 17 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 5 minutes, 46 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 5 minutes, 9 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 4 minutes, 36 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 3 minutes, 59 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 3 minutes, 26 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 2 minutes, 55 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 2 minutes, 26 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 1 minute, 55 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 23 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 53 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 22 seconds.
20250922 134614	414	10	877	38	5	53946000	100

[mbo] 84: num.trees=414; max.depth=10; min.node.size=877; mtry=38 : y = 5.39e+07 : 1867.7 secs : infill_ei

Saved the current state after iteration 85 in the file HT450.RDATA.

Growing trees.. Progress: 6%. Estimated remaining time: 8 minutes, 6 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 7 minutes, 33 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 7 minutes, 1 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 6 minutes, 24 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 5 minutes, 53 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 5 minutes, 20 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 4 minutes, 50 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 4 minutes, 17 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 3 minutes, 45 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 3 minutes, 14 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 2 minutes, 42 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 2 minutes, 11 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 1 minute, 39 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 37 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 5 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 8 minutes, 48 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 8 minutes, 25 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 7 minutes, 36 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 7 minutes, 2 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 6 minutes, 27 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 5 minutes, 55 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 5 minutes, 22 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 4 minutes, 48 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 4 minutes, 13 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 3 minutes, 40 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 3 minutes, 7 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 2 minutes, 33 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 2 minutes, 2 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 31 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 59 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 28 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 8 minutes, 48 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 8 minutes, 0 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 7 minutes, 20 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 6 minutes, 53 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 6 minutes, 17 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 5 minutes, 44 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 5 minutes, 10 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 4 minutes, 39 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 4 minutes, 5 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 3 minutes, 33 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 3 minutes, 3 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 2 minutes, 34 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 2 minutes, 1 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 32 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 1 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 29 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 8 minutes, 22 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 7 minutes, 40 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 7 minutes, 7 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 6 minutes, 40 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 6 minutes, 5 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 5 minutes, 32 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 4 minutes, 58 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 4 minutes, 25 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 3 minutes, 52 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 3 minutes, 19 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 2 minutes, 47 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 2 minutes, 15 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 1 minute, 45 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 14 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 46 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 18 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 8 minutes, 43 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 7 minutes, 53 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 7 minutes, 25 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 6 minutes, 49 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 6 minutes, 16 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 5 minutes, 42 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 5 minutes, 6 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 4 minutes, 33 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 3 minutes, 57 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 3 minutes, 23 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 2 minutes, 50 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 2 minutes, 18 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 1 minute, 46 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 15 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 44 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 12 seconds.
20250922 143113	451	10	391	50	5	55227000	101

[mbo] 85: num.trees=451; max.depth=10; min.node.size=391; mtry=50 : y = 5.52e+07 : 2694.6 secs : infill_ei

Saved the current state after iteration 86 in the file HT450.RDATA.

Growing trees.. Progress: 22%. Estimated remaining time: 1 minute, 49 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 1 minute, 21 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 51 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 21 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 1 minute, 54 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 1 minute, 23 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 53 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 22 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 1 minute, 52 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 1 minute, 21 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 50 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 18 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 1 minute, 52 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 55 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 23 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 1 minute, 57 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 54 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 23 seconds.
20250922 144425	268	28	1000	14	5	54660000	102

[mbo] 86: num.trees=268; max.depth=28; min.node.size=1000; mtry=14 : y = 5.47e+07 : 784.7 secs : infill_ei

Saved the current state after iteration 87 in the file HT450.RDATA.

Growing trees.. Progress: 20%. Estimated remaining time: 2 minutes, 9 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 1 minute, 37 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 29 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 2 minutes, 1 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 1 minute, 28 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 57 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 25 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 1 minute, 57 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 54 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 23 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 2 minutes, 5 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 1 minute, 34 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 1 minute, 0 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 29 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 2 minutes, 5 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 1 minute, 31 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 58 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 26 seconds.
20250922 145756	192	25	490	19	5	53991000	103

[mbo] 87: num.trees=192; max.depth=25; min.node.size=490; mtry=19 : y = 5.4e+07 : 806.7 secs : infill_ei

Saved the current state after iteration 88 in the file HT450.RDATA.

Growing trees.. Progress: 5%. Estimated remaining time: 10 minutes, 49 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 9 minutes, 58 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 9 minutes, 36 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 9 minutes, 8 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 8 minutes, 40 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 8 minutes, 4 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 7 minutes, 30 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 6 minutes, 55 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 6 minutes, 25 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 5 minutes, 54 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 5 minutes, 19 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 4 minutes, 48 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 4 minutes, 17 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 3 minutes, 45 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 3 minutes, 10 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 2 minutes, 38 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 2 minutes, 6 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 33 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 1 minute, 3 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 10 minutes, 30 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 9 minutes, 48 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 9 minutes, 11 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 8 minutes, 44 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 8 minutes, 8 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 7 minutes, 36 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 7 minutes, 8 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 6 minutes, 39 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 6 minutes, 11 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 5 minutes, 45 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 5 minutes, 17 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 4 minutes, 49 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 4 minutes, 18 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 3 minutes, 44 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 3 minutes, 13 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 2 minutes, 40 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 2 minutes, 8 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 37 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 1 minute, 3 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 10 minutes, 39 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 10 minutes, 3 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 9 minutes, 30 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 9 minutes, 4 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 8 minutes, 42 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 8 minutes, 17 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 7 minutes, 55 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 7 minutes, 34 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 7 minutes, 16 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 6 minutes, 47 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 6 minutes, 26 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 5 minutes, 56 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 5 minutes, 23 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 4 minutes, 47 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 4 minutes, 9 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 3 minutes, 33 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 2 minutes, 59 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 2 minutes, 24 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 50 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 1 minute, 17 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 43 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 10 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 10 minutes, 49 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 9 minutes, 53 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 9 minutes, 13 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 8 minutes, 44 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 8 minutes, 10 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 7 minutes, 36 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 7 minutes, 2 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 6 minutes, 30 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 5 minutes, 55 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 5 minutes, 22 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 4 minutes, 49 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 4 minutes, 17 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 3 minutes, 44 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 3 minutes, 12 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 2 minutes, 39 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 2 minutes, 7 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 35 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 17 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 44 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 11 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 10 minutes, 39 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 10 minutes, 18 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 9 minutes, 43 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 9 minutes, 7 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 8 minutes, 30 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 7 minutes, 57 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 7 minutes, 22 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 6 minutes, 50 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 6 minutes, 15 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 5 minutes, 42 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 5 minutes, 9 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 4 minutes, 36 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 4 minutes, 2 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 3 minutes, 29 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 2 minutes, 55 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 2 minutes, 20 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 47 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 1 minute, 13 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 8 seconds.
20250922 155500	476	12	701	50	5	55188000	104

[mbo] 88: num.trees=476; max.depth=12; min.node.size=701; mtry=50 : y = 5.52e+07 : 3416.7 secs : infill_ei

Saved the current state after iteration 89 in the file HT450.RDATA.

Growing trees.. Progress: 19%. Estimated remaining time: 2 minutes, 13 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 1 minute, 41 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 38 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 7 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 2 minutes, 11 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 1 minute, 41 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 1 minute, 8 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 36 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 5 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 2 minutes, 13 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 1 minute, 42 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 1 minute, 10 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 8 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 2 minutes, 11 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 1 minute, 40 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 38 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 7 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 2 minutes, 13 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 1 minute, 42 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 1 minute, 11 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 10 seconds.
20250922 160933	298	20	885	15	5	54339000	105

[mbo] 89: num.trees=298; max.depth=20; min.node.size=885; mtry=15 : y = 5.43e+07 : 867.4 secs : infill_ei

Saved the current state after iteration 90 in the file HT450.RDATA.

Growing trees.. Progress: 33%. Estimated remaining time: 1 minute, 3 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 31 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 1 minute, 14 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 45 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 12 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 1 minute, 6 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 35 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 4 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 1 minute, 23 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 44 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 11 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 1 minute, 8 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 35 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 4 seconds.
20250922 161845	407	9	200	10	5	54231000	106

[mbo] 90: num.trees=407; max.depth=9; min.node.size=200; mtry=10 : y = 5.42e+07 : 547.6 secs : infill_ei

Growing trees.. Progress: 9%. Estimated remaining time: 5 minutes, 32 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 5 minutes, 1 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 4 minutes, 26 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 3 minutes, 55 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 3 minutes, 26 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 2 minutes, 52 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 2 minutes, 23 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 1 minute, 52 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 21 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 50 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 18 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 5 minutes, 41 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 4 minutes, 56 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 4 minutes, 29 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 3 minutes, 58 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 3 minutes, 32 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 3 minutes, 8 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 2 minutes, 42 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 2 minutes, 11 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 1 minute, 42 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 1 minute, 11 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 42 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 13 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 6 minutes, 40 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 5 minutes, 56 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 5 minutes, 41 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 5 minutes, 2 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 4 minutes, 19 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 3 minutes, 48 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 3 minutes, 13 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 2 minutes, 43 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 2 minutes, 8 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 35 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 1 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 29 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 5 minutes, 22 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 4 minutes, 51 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 4 minutes, 23 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 3 minutes, 58 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 3 minutes, 26 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 3 minutes, 3 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 2 minutes, 33 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 2 minutes, 5 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 1 minute, 34 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 4 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 31 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 5 minutes, 33 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 4 minutes, 56 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 4 minutes, 26 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 3 minutes, 55 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 3 minutes, 24 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 2 minutes, 51 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 2 minutes, 20 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 1 minute, 49 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 1 minute, 17 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 45 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 13 seconds.
20250922 165119	445	10	191	35	5	54774000	107

[mbo] 91: num.trees=445; max.depth=10; min.node.size=191; mtry=35 : y = 5.48e+07 : 1953.3 secs : infill_ei

Saved the current state after iteration 92 in the file HT450.RDATA.

Growing trees.. Progress: 5%. Estimated remaining time: 9 minutes, 36 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 8 minutes, 47 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 8 minutes, 15 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 7 minutes, 46 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 7 minutes, 12 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 6 minutes, 37 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 6 minutes, 0 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 5 minutes, 27 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 4 minutes, 52 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 4 minutes, 17 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 3 minutes, 43 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 3 minutes, 10 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 2 minutes, 36 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 2 minutes, 3 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 31 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 59 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 29 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 9 minutes, 36 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 8 minutes, 48 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 8 minutes, 15 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 7 minutes, 42 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 7 minutes, 6 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 6 minutes, 32 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 5 minutes, 58 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 5 minutes, 28 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 4 minutes, 53 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 4 minutes, 19 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 3 minutes, 46 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 3 minutes, 13 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 2 minutes, 41 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 2 minutes, 9 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 36 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 29 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 9 minutes, 1 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 8 minutes, 9 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 7 minutes, 45 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 7 minutes, 13 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 6 minutes, 41 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 6 minutes, 9 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 5 minutes, 37 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 5 minutes, 5 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 4 minutes, 34 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 4 minutes, 2 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 3 minutes, 30 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 2 minutes, 58 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 2 minutes, 25 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 1 minute, 54 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 23 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 51 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 19 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 9 minutes, 19 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 8 minutes, 32 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 7 minutes, 55 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 7 minutes, 20 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 6 minutes, 47 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 6 minutes, 12 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 5 minutes, 44 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 5 minutes, 11 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 4 minutes, 38 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 4 minutes, 6 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 3 minutes, 34 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 3 minutes, 1 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 2 minutes, 29 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 1 minute, 59 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 27 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 54 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 20 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 9 minutes, 1 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 8 minutes, 24 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 7 minutes, 50 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 7 minutes, 17 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 6 minutes, 44 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 6 minutes, 12 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 5 minutes, 40 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 5 minutes, 7 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 4 minutes, 34 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 4 minutes, 2 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 3 minutes, 30 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 3 minutes, 0 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 2 minutes, 28 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 1 minute, 57 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 20 seconds.
20250922 173951	351	14	506	50	5	54627000	108

[mbo] 92: num.trees=351; max.depth=14; min.node.size=506; mtry=50 : y = 5.46e+07 : 2904.4 secs : infill_ei

Saved the current state after iteration 93 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 991 points instead of 1000!”

Growing trees.. Progress: 23%. Estimated remaining time: 1 minute, 43 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 1 minute, 11 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 8 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 1 minute, 45 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 1 minute, 12 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 9 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 1 minute, 45 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 1 minute, 12 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 42 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 13 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 1 minute, 45 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 1 minute, 14 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 42 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 12 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 1 minute, 45 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 1 minute, 13 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 41 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 9 seconds.
20250922 175206	339	15	497	11	5	53853000	109

[mbo] 93: num.trees=339; max.depth=15; min.node.size=497; mtry=11 : y = 5.39e+07 : 730.6 secs : infill_ei

Saved the current state after iteration 94 in the file HT450.RDATA.

Growing trees.. Progress: 7%. Estimated remaining time: 6 minutes, 48 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 6 minutes, 17 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 5 minutes, 42 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 5 minutes, 11 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 4 minutes, 40 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 4 minutes, 8 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 3 minutes, 38 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 3 minutes, 8 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 2 minutes, 37 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 2 minutes, 5 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 1 minute, 34 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 3 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 31 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 6 minutes, 48 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 6 minutes, 23 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 5 minutes, 50 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 5 minutes, 21 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 4 minutes, 51 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 4 minutes, 23 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 3 minutes, 49 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 3 minutes, 17 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 2 minutes, 45 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 2 minutes, 13 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 40 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 7 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 36 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 3 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 7 minutes, 1 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 6 minutes, 29 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 5 minutes, 58 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 5 minutes, 23 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 4 minutes, 49 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 4 minutes, 18 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 3 minutes, 48 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 3 minutes, 17 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 2 minutes, 44 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 2 minutes, 12 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 41 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 10 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 9 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 7 minutes, 32 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 7 minutes, 8 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 7 minutes, 29 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 6 minutes, 37 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 5 minutes, 49 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 5 minutes, 10 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 4 minutes, 32 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 3 minutes, 57 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 3 minutes, 30 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 3 minutes, 0 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 2 minutes, 29 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 1 minute, 57 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 19 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 7 minutes, 47 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 7 minutes, 8 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 6 minutes, 38 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 5 minutes, 57 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 5 minutes, 17 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 4 minutes, 44 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 4 minutes, 12 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 3 minutes, 44 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 3 minutes, 11 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 2 minutes, 37 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 2 minutes, 3 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 1 minute, 31 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
20250922 183200	468	16	372	25	5	55218000	110

[mbo] 94: num.trees=468; max.depth=16; min.node.size=372; mtry=25 : y = 5.52e+07 : 2385.2 secs : infill_ei

Saved the current state after iteration 95 in the file HT450.RDATA.

Growing trees.. Progress: 7%. Estimated remaining time: 7 minutes, 5 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 6 minutes, 33 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 6 minutes, 1 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 5 minutes, 30 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 4 minutes, 58 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 4 minutes, 27 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 3 minutes, 58 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 3 minutes, 27 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 2 minutes, 56 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 2 minutes, 25 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 1 minute, 52 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 21 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 50 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 19 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 8 minutes, 4 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 7 minutes, 17 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 6 minutes, 35 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 5 minutes, 58 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 5 minutes, 23 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 4 minutes, 48 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 4 minutes, 15 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 3 minutes, 39 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 3 minutes, 7 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 2 minutes, 34 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 2 minutes, 1 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 59 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 25 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 6 minutes, 51 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 6 minutes, 20 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 5 minutes, 53 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 5 minutes, 24 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 4 minutes, 54 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 4 minutes, 21 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 3 minutes, 52 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 3 minutes, 19 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 2 minutes, 46 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 2 minutes, 14 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 41 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 37 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 7 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 7 minutes, 18 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 6 minutes, 54 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 6 minutes, 29 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 5 minutes, 54 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 5 minutes, 17 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 4 minutes, 42 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 4 minutes, 6 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 3 minutes, 36 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 3 minutes, 8 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 2 minutes, 35 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 2 minutes, 2 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 58 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 25 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 7 minutes, 18 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 6 minutes, 53 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 6 minutes, 20 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 5 minutes, 44 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 5 minutes, 10 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 4 minutes, 37 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 4 minutes, 6 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 3 minutes, 35 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 3 minutes, 3 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 2 minutes, 29 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 1 minute, 55 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 22 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 50 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 18 seconds.
20250922 191146	500	14	415	26	5	54093000	111

[mbo] 95: num.trees=500; max.depth=14; min.node.size=415; mtry=26 : y = 5.41e+07 : 2380.1 secs : infill_ei

Saved the current state after iteration 96 in the file HT450.RDATA.

Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 53 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 4 minutes, 14 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 3 minutes, 43 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 3 minutes, 9 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 2 minutes, 40 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 2 minutes, 7 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 1 minute, 38 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 11 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 5 minutes, 8 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 4 minutes, 33 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 4 minutes, 1 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 3 minutes, 29 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 2 minutes, 56 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 2 minutes, 21 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 1 minute, 45 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 11 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 38 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 4 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 32 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 4 minutes, 1 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 3 minutes, 32 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 3 minutes, 1 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 2 minutes, 30 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 1 minute, 58 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 1 minute, 26 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 54 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 23 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 39 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 4 minutes, 4 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 3 minutes, 32 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 3 minutes, 2 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 2 minutes, 31 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 2 minutes, 1 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 1 minute, 29 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 56 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 26 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 39 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 4 minutes, 22 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 4 minutes, 17 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 4 minutes, 14 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 4 minutes, 14 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 3 minutes, 46 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 3 minutes, 8 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 2 minutes, 21 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 1 minute, 37 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 56 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 17 seconds.
20250922 194002	460	16	636	18	5	54858000	112

[mbo] 96: num.trees=460; max.depth=16; min.node.size=636; mtry=18 : y = 5.49e+07 : 1690.4 secs : infill_ei

Saved the current state after iteration 97 in the file HT450.RDATA.

Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 41 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 3 minutes, 13 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 2 minutes, 41 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 2 minutes, 12 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 1 minute, 40 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 1 minute, 10 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 8 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 53 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 3 minutes, 13 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 2 minutes, 41 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 2 minutes, 7 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 1 minute, 36 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 1 minute, 4 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 32 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 2 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 41 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 3 minutes, 8 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 2 minutes, 35 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 2 minutes, 4 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 1 minute, 31 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 58 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 26 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 3 minutes, 31 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 3 minutes, 0 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 2 minutes, 28 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 1 minute, 57 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 1 minute, 26 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 54 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 23 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 3 minutes, 31 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 3 minutes, 0 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 2 minutes, 28 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 1 minute, 56 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 54 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 23 seconds.
20250922 200151	367	16	299	18	5	54360000	113

[mbo] 97: num.trees=367; max.depth=16; min.node.size=299; mtry=18 : y = 5.44e+07 : 1304.7 secs : infill_ei

Saved the current state after iteration 98 in the file HT450.RDATA.

Growing trees.. Progress: 29%. Estimated remaining time: 1 minute, 16 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 44 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 13 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 1 minute, 12 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 42 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 11 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 1 minute, 15 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 44 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 15 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 1 minute, 19 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 45 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 14 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 1 minute, 15 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 43 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 12 seconds.
20250922 201144	278	17	415	10	5	54759000	114

[mbo] 98: num.trees=278; max.depth=17; min.node.size=415; mtry=10 : y = 5.48e+07 : 584.4 secs : infill_ei

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 994 points instead of 1000!”

Growing trees.. Progress: 5%. Estimated remaining time: 10 minutes, 43 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 10 minutes, 16 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 9 minutes, 54 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 9 minutes, 23 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 8 minutes, 53 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 8 minutes, 21 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 7 minutes, 52 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 7 minutes, 20 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 6 minutes, 46 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 6 minutes, 13 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 5 minutes, 40 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 5 minutes, 9 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 4 minutes, 35 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 4 minutes, 1 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 3 minutes, 27 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 2 minutes, 55 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 2 minutes, 23 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 51 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 1 minute, 18 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 45 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 13 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 12 minutes, 17 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 11 minutes, 56 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 11 minutes, 48 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 11 minutes, 40 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 11 minutes, 8 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 10 minutes, 44 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 9 minutes, 57 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 9 minutes, 7 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 8 minutes, 22 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 7 minutes, 38 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 6 minutes, 59 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 6 minutes, 23 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 5 minutes, 48 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 5 minutes, 9 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 4 minutes, 30 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 3 minutes, 54 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 3 minutes, 21 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 2 minutes, 46 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 2 minutes, 13 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 1 minute, 39 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 1 minute, 7 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 11 minutes, 54 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 10 minutes, 49 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 10 minutes, 5 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 9 minutes, 54 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 9 minutes, 23 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 8 minutes, 55 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 8 minutes, 24 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 8 minutes, 11 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 8 minutes, 10 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 8 minutes, 9 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 8 minutes, 2 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 7 minutes, 28 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 6 minutes, 55 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 6 minutes, 31 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 6 minutes, 3 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 5 minutes, 36 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 5 minutes, 8 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 4 minutes, 39 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 4 minutes, 5 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 3 minutes, 26 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 2 minutes, 50 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 2 minutes, 21 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 1 minute, 47 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 1 minute, 14 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 38 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 3 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 12 minutes, 40 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 11 minutes, 45 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 11 minutes, 0 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 10 minutes, 17 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 9 minutes, 31 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 8 minutes, 53 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 8 minutes, 19 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 7 minutes, 46 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 7 minutes, 12 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 6 minutes, 47 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 6 minutes, 18 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 5 minutes, 46 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 5 minutes, 26 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 5 minutes, 5 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 4 minutes, 42 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 4 minutes, 13 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 3 minutes, 39 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 3 minutes, 9 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 2 minutes, 34 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 56 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 1 minute, 21 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 47 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 11 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 11 minutes, 54 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 10 minutes, 56 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 10 minutes, 23 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 9 minutes, 40 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 9 minutes, 13 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 8 minutes, 38 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 8 minutes, 4 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 7 minutes, 28 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 6 minutes, 55 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 6 minutes, 21 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 5 minutes, 52 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 5 minutes, 22 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 4 minutes, 52 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 4 minutes, 17 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 3 minutes, 44 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 3 minutes, 12 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 2 minutes, 40 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 2 minutes, 7 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 35 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 1 minute, 1 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 29 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
20250922 211527	457	16	465	40	5	55464000	115
20250922 211528	457	16	465	40	5	55464000	115

[mbo] 99: num.trees=457; max.depth=16; min.node.size=465; mtry=40 : y = 5.55e+07 : 3824.2 secs : infill_ei

Saved the current state after iteration 100 in the file HT450.RDATA.

Growing trees.. Progress: 4%. Estimated remaining time: 11 minutes, 56 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 11 minutes, 13 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 10 minutes, 38 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 10 minutes, 27 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 9 minutes, 45 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 9 minutes, 13 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 8 minutes, 45 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 8 minutes, 14 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 7 minutes, 38 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 7 minutes, 2 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 6 minutes, 30 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 5 minutes, 56 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 5 minutes, 22 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 4 minutes, 49 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 4 minutes, 14 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 3 minutes, 41 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 3 minutes, 9 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 2 minutes, 36 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 2 minutes, 3 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 31 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 59 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 28 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 12 minutes, 46 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 11 minutes, 35 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 10 minutes, 51 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 10 minutes, 32 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 9 minutes, 49 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 9 minutes, 21 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 8 minutes, 52 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 8 minutes, 28 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 7 minutes, 57 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 7 minutes, 30 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 6 minutes, 57 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 6 minutes, 26 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 5 minutes, 54 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 5 minutes, 22 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 4 minutes, 50 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 4 minutes, 18 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 3 minutes, 46 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 3 minutes, 10 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 2 minutes, 36 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 2 minutes, 4 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 31 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 57 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 23 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 11 minutes, 56 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 11 minutes, 2 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 10 minutes, 38 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 10 minutes, 4 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 9 minutes, 31 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 8 minutes, 57 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 8 minutes, 20 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 7 minutes, 48 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 7 minutes, 18 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 6 minutes, 47 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 6 minutes, 17 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 5 minutes, 49 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 5 minutes, 19 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 4 minutes, 49 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 4 minutes, 19 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 3 minutes, 49 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 3 minutes, 19 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 2 minutes, 45 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 2 minutes, 17 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 44 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 1 minute, 13 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 44 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 15 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 12 minutes, 46 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 11 minutes, 35 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 10 minutes, 37 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 10 minutes, 3 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 9 minutes, 30 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 9 minutes, 1 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 8 minutes, 35 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 8 minutes, 5 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 7 minutes, 33 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 7 minutes, 5 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 6 minutes, 30 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 5 minutes, 58 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 5 minutes, 22 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 4 minutes, 49 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 4 minutes, 17 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 3 minutes, 43 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 3 minutes, 11 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 2 minutes, 38 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 2 minutes, 6 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 31 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 57 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 22 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 11 minutes, 56 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 11 minutes, 36 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 11 minutes, 0 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 10 minutes, 18 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 9 minutes, 40 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 9 minutes, 5 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 8 minutes, 36 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 8 minutes, 5 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 7 minutes, 40 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 7 minutes, 12 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 6 minutes, 41 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 6 minutes, 10 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 5 minutes, 38 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 5 minutes, 4 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 4 minutes, 32 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 4 minutes, 4 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 3 minutes, 33 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 3 minutes, 4 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 2 minutes, 32 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 2 minutes, 0 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 1 minute, 24 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 53 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 21 seconds.
20250922 221918	386	16	411	50	5	54540000	116

[mbo] 100: num.trees=386; max.depth=16; min.node.size=411; mtry=50 : y = 5.45e+07 : 3822.4 secs : infill_ei

Saved the final state in the file HT450.RDATA

Saved the final state in the file HT450.RDATA

In [40]:
# analizo la salida de la bayesiana

tb_bayesiana <- fread(klog)
setorder( tb_bayesiana, -ganancia)
tb_bayesiana

    fecha           num.trees max.depth min.node.size mtry xval_folds ganancia
1   20250922 211527 457       16         465          40   5          55464000
2   20250922 131500 327       16         432          11   5          55431000
3   20250920 234550 490       16         787          27   5          55371000
4   20250922 033821 338       16         833          11   5          55263000
5   20250922 102304 498       24         859          14   5          55230000
6   20250922 143113 451       10         391          50   5          55227000
7   20250922 020337 146       28         458          17   5          55218000
8   20250922 183200 468       16         372          25   5          55218000
9   20250922 121813 454       10         763          50   5          55215000
10  20250922 043111 488       14         496          39   5          55209000
11  20250922 113103 385       14         357          26   5          55197000
12  20250922 031630 500       30         843          15   5          55191000
13  20250922 155500 476       12         701          50   5          55188000
14  20250921 183757 376       10         219          11   5          55158000
15  20250922 064905 500       12         486          37   5          55137000
16  20250921 164836 500       25         903          28   5          55095000
17  20250921 052602 500       13         731          24   5          55071000
18  20250922 110236 460       15         436          18   5          55071000
19  20250922 103751 247       26         454          17   5          55050000
20  20250921 142148 409       12         727          26   5          55035000
21  20250921 110650 372       12         438          11   5          55032000
22  20250921 061828 500       19        1000          33   5          55020000
23  20250922 094841 438       13         432          41   5          54999000
24  20250921 010543 147       26         358          21   5          54996000
25  20250921 151301 500       15         806          35   5          54960000
26  20250922 032743 230       30         903          16   5          54891000
27  20250922 194002 460       16         636          18   5          54858000
28  20250922 050723 476       14         813          27   5          54852000
29  20250921 113728 500       27        1000          18   5          54849000
30  20250922 090040 399        9         213          33   5          54840000
⋮   ⋮               ⋮         ⋮         ⋮             ⋮    ⋮          ⋮
87  20250922 175206 339       15         497          11   5          53853000
88  20250921 062359 253       30         711           3   5          53793000
89  20250921 075931 417       19         277           2   5          53724000
90  20250922 065910 166       27         371          18   5          53682000
91  20250922 122644 500       16         838           4   5          53679000
92  20250921 025004 186       14         884           4   5          53664000
93  20250921 214459 473       19         733          30   5          53655000
94  20250921 064549 109       26         798           8   5          53577000
95  20250921 012906 265        8         498           9   5          53535000
96  20250920 230913 118       10         417          34   5          53445000
97  20250921 160319 500       30        1000           2   5          53286000
98  20250921 003030 251       28         624          41   5          53211000
99  20250921 033222  20       26        1000           5   5          52956000
100 20250921 102210 158       28         213           2   5          52929000
101 20250921 005143 211       20         129          30   5          52776000
102 20250921 075452 486       15           1          31   5          52692000
103 20250921 012449 334       24         102          17   5          52551000
104 20250921 142542 500       11         322           2   5          52518000
105 20250921 173350  78       18         404           2   5          52389000
106 20250922 081539 375       12         145           2   5          52167000
107 20250921 005507  71        6         977          49   5          52110000
108 20250921 024708 376       30         225          37   5          51651000
109 20250921 172626 149       23         418          50   5          51549000
110 20250921 030342  34        4          20           5   5          51339000
111 20250921 080248 488       10        1000           2   5          51105000
112 20250921 062033  20       25         550          28   5          50829000
113 20250922 083759  41       25         301          14   5          50787000
114 20250922 081651  20       29         564          15   5          50586000
115 20250921 091152 472        1         805          33   5          44133000
116 20250921 015602 315        1         536          46   5          43020000
    iteracion
1   115
2    99
3     2
4    75
5    92
6   101
7    71
8   110
9    96
10   76
11   95
12   73
13  104
14   58
15   79
16   50
17   20
18   94
19   93
20   44
21   37
22   21
23   90
24    7
25   46
26   74
27  112
28   77
29   38
30   89
⋮   ⋮
87  109
88   23
89   28
90   80
91   97
92   13
93   62
94   25
95    9
96    1
97   49
98    4
99   17
100  35
101   5
102  27
103   8
104  45
105  54
106  85
107   6
108  12
109  52
110  15
111  29
112  22
113  88
114  86
115  32
116  11

In [41]:
# mejores parametros

print( tb_bayesiana[1] )

             fecha num.trees max.depth min.node.size  mtry xval_folds ganancia
            <char>     <int>     <int>         <int> <int>      <int>    <int>
1: 20250922 211527       457        16           465    40          5 55464000
   iteracion
       <int>
1:       115

In [42]:
format(Sys.time(), "%a %b %d %X %Y")

[1] "Mon Sep 22 22:19:30 2025"



---